### ISSUE TITLE
Difference between self.results.buffername and self.results['buffername']

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#1000]
`UDFData` implements both `__getitem__()` and `__getattr__()`. The former returns a `BufferWrapper` object, the latter a view into the memory of the underlying data array. 

This can be a bit confusing:

* When merging results in an UDF's `process_*()`method: Use `self.results.buffername` to get the proper view.
* When inside a UDF's `merge()` function: Use sth like `dest['buffername'][:] = dest['buffername'] + src['buffername']` since the buffers are passed in as `Dict`.
* When in `get_results()`: Use `self.results['buffername']` to pass through a `BufferWrapper`, but use `self.result('buffername', some_operation(self.results.buffername))` for a final postprocessing step. Alternatively, use `self.results['buffername'].raw_data` instead of self.results.buffername

**Comment by sk1p** [comment]
Related: #631

**Comment by sk1p** [comment]
How about we fix this together with #1001?

> When merging results in an UDF's `process_*()` method: Use `self.results.buffername` to get the proper view

I think this is the okay and can stay like this.

> When inside a UDF's `merge()` function: Use sth like `dest['buffername'][:] = dest['buffername'] + src['buffername']` since the buffers are passed in as Dict.

Actually a `MappingProxyType`, which is slightly different, and used for making the dict readonly. This could be changed to a different object that also allows attribute access (to fix #631), which then should return the view, as it should

> When in `get_results()`: Use `self.results['buffername']` to pass through a `BufferWrapper`, but use `self.result('buffername', some_operation(self.results.buffername))` for a final postprocessing step. Alternatively, use `self.results['buffername'].raw_data` instead of `self.results.buffername`

Hmm. This makes me think we may want to remove the `__getitem__` way of getting a `ResultBuffer`, and make that more explicit? Letting `self.results.get_buffer('buffername')`  return the `ResultBuffer`, and `self.results.buffername` return the current view, as usual? Maybe you also have a better idea to get at the raw data of a buffer?
