### ISSUE TITLE
GPU usage when workers are idle?

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#1065]
Via @jhgee: need to investigate if GPU usage properly winds down when tasks are done, but workers are still running:

![](https://files.gitter.im/5ebd0dccd73408ce4fe3b997/BPWG/grafik.png)

![](https://files.gitter.im/5ebd0dccd73408ce4fe3b997/H1Qh/grafik.png)

**Comment by uellue** [comment]
@jhgee do you have more information how to reproduce this? I haven't observed that yet on our systems.

**Comment by jhgee** [comment]
@uellue I will try out some more things with our system the next time

**Comment by sk1p** [comment]
> I will try out some more things with our system the next time

Thanks, much appreciated!
