### ISSUE TITLE
Non-standard characters in path trip MIB reader

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#1066]
## How to reproduce

Try to open an MIB dataset via the HDR file where the path contains, for example, square brackets.

## What happens

`get_filenames()`

https://github.com/LiberTEM/LiberTEM/blob/6b6ca850fd71ba3f00ed420267b7d97311343394/src/libertem/io/dataset/mib.py#L94-L107

fails to find the MIB files and returns an empty list:

```python

from libertem.io.dataset.mib import get_filenames

get_filenames(r'E:\LargeData\LargeData\ER-C-1\groups\data_science\data\reference\MIB[FAIL]\20200518 165148\default.hdr')

[]
```

It works if the folder `MIB[FAIL]` is renamed to `MIB`.

## What should happen

All characters that can "legally" be part of a file system path work.

We should also check other multi-file datasets such as K2IS and FRMS6 if they suffer from a similar issue. Probably the globs or regexp should be fixed. We should also test that in CI.

**Comment by sk1p** [comment]
Ah, that makes sense! Thanks for looking into this. We can `glob.escape` the prefix, before adding the `*.mib`.
