### ISSUE TITLE
Word wrap for table cells

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#1071]
The table cells in https://libertem.github.io/LiberTEM/sample_datasets.html are currently not wrapping.

This could be an issue with the theme?

**Comment by sk1p** [comment]
> This could be an issue with the theme?

This is generally an issue with tables - it's hard to have a working default styling that covers all cases in a sane way. I think we should instead just not use a table. Could a list work better maybe? Similar but simpler than our [funding section](https://libertem.github.io/LiberTEM/acknowledgments.html#funding)? 

That way, we don't have to fit long dataset names into the horizontal space, while still displaying the other columns...

**Comment by uellue** [comment]
> Could a list work better maybe? Similar but simpler than our [funding section](https://libertem.github.io/LiberTEM/acknowledgments.html#funding)?

Sounds good, would also be much easier to edit in the source code. I've made it a "good first issue" now. :-)
