### ISSUE TITLE
Open a Dataset via command line parameters, URL parameters and possibly embed in other web applications.

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#1085]
Starting and accessing LiberTEM through JupyterHub and JupyterLab #1074 makes sure that LiberTEM runs as the correct Unix user. It delegates authentication to JupyterHub/Lab and authorization to the operating system via Unix users and file permissions.

Since the URL for LiberTEM for a specific user is predictable, such as https://example.com/user/weber/libertem/, we could link to datasets from an electronic lab notebook (ELN) or other web application. On the ELN side we'd just have to know the username, a storage path and possibly parameters. On LiberTEM side we just need to accept the storage path and dataset parameters somehow, for example through URL parameters.

Furthermore, other integration, namely in the Australian CVL, can require opening a file via command line parameters.

Possibly that would even allow embedding the GUI resp. GUI elements?

**Comment by uellue** [comment]
Moved to the 0.9 milestone since there is specific demand from University of Queensland users and it looks like a relatively simple feature with large benefit for users. :-)

**Comment by sk1p** [comment]
No need to include the username in the URL, this works, too: https://your-jupyter-hub/user-redirect/libertem/

**Comment by uellue** [comment]
Refs #867

**Comment by uellue** [comment]
Integration work by @shabihsherjeel depends on this feature. If I understood correctly, the timeline is flexible for now? In any case, an important feature for the next release and should definitely be shortlisted. :-)

**Comment by shabihsherjeel** [comment]
Yeah. I had the cli option setup on a local branch. It's nice to see this being implemented. I will keep an eye out for this and use it to run it in other projects that load LiberTEM. Thanks for letting me know. :)

**Comment by uellue** [comment]
Discussion with @sk1p: We should also provide an interface to start a cluster or connect to one without user interaction for integrations like this.

**Comment by uellue** [comment]
Moved to the 0.10 milestone so that we get the executor and Dask integration work out first.

**Comment by uellue** [comment]
It seems like this is solved in #1518? For the data management at ER-C we figured that linking is better than embedding since it introduces less dependencies, is way more general and works nearly as well.
