### ISSUE TITLE
Mismatch between number of 'available' Dask workers and partitions for small datasets

### ISSUE THREAD

**Issue by matbryan52** [LiberTEM/LiberTEM#1086]
In diving into the executors, I believe I've found an oversight in the Dask worker creation / Dataset partitioning interaction.

In executors/dask.py/DaskJobExecutor.make_local() we have:
```python
spec = cluster_spec(**detect())
```
which defines a cluster spec based on available resources on the current node. For a dual core (2 physical/4 HT) machine with no GPU by default this specifies two compute workers (each with one CPU core) and one 'service' worker (with no resources).

After spin up, `executor.get_available_workers()` returns a `WorkerSet` of length 3. This is fine, as I don't think Dask will ever send work to the worker with no resources. However, elsewhere in the code for dataset initialization (io/dataset/__init__.py), we have:
```python
ds.set_num_cores(len(executor.get_available_workers()))
```
which sets the `self._cores` attribute of the dataset. This attribute seems to be used in most versions of the method `get_num_partitions()`, in the following way:
```python
num_partitions = max(self._cores, total_size_px // partition_size_px)
```
which means that for small datasets (few partitions) we end up with one extra partition compared to the number of actual compute workers.

It's clearly not a big deal, as in most cases `total_size_px // partition_size_px > self._cores` anyway. That said, I haven't checked all of the instances where `get_available_workers` is called to see if there are other consequences.

The fix is easy, perhaps just a modification to `get_available_workers` allowing it to return the number of CPU-allocated workers when needed.

**Comment by uellue** [comment]
@matbryan52 why did you label the Issue as "invalid"? Or do you mean the behavior is wrong? The issue you describe sounds valid and indeed easy to fix. :-)
