### ISSUE TITLE
Autodetection of SEQ dark, gain and dead pixel maps apparently not working with our reference dataset

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#1120]
## How to reproduce

* Open our reference SEQ dataset like this and inspect the corrections:

```python

params = {'path': '/Users/weber/LargeData/ER-C-1/groups/data_science/data/reference/SEQ/2020-05-04 8x8 8fps 128x128 streampix 8.seq.seq',
          'nav_shape': [8, 8], 'sig_shape': (128, 128), 'sync_offset': 0}

ds = ctx.load("SEQ", **params)

ds.get_correction_data().have_corrections()

# False
```

Listing of `/Users/weber/LargeData/ER-C-1/groups/data_science/data/reference/SEQ/`:

```
2020-05-04 8x8 8fps 128x128 streampix 8.seq.Config.Metadata.xml
2020-05-04 8x8 8fps 128x128 streampix 8.seq.dark.mrc
2020-05-04 8x8 8fps 128x128 streampix 8.seq.gain.mrc
2020-05-04 8x8 8fps 128x128 streampix 8.seq.metadata
2020-05-04 8x8 8fps 128x128 streampix 8.seq.seq
```

The GUI also shows patterns consistent with uncorrected gain and dark.

## What should happen

Following [our documentation](https://libertem.github.io/LiberTEM/reference/dataset.html#seq), the correction data should be loaded from the available files.

**Comment by uellue** [comment]
In our data management reference folder, the file is named `*.seq.seq`, while in the folder for unit tests it is called `*.seq`. Both file sets have exactly the same size each, so I figure it is the same source? @sk1p I'll just assume that the file got renamed by accident? Can you perhaps fix that in the unit test data and rename it `default.seq`-> `default.seq.seq` since I don't have write permission there? I'll fix the discovery code.

**Comment by sk1p** [comment]
> Can you perhaps fix that in the unit test data and rename it default.seq-> default.seq.seq since I don't have write permission there? I'll fix the discovery code.

I'm not convinced that this is the right course of action - the other SEQ dataset I have available doesn't have the ".seq.seq" ending, so I think `2020-05-04 8x8 8fps 128x128 streampix 8.seq.seq` is the one that is wrong.

**Comment by uellue** [comment]
Maybe I can just make it work with both `.seq` and `.seq seq` then? 😊

**Comment by sk1p** [comment]
> Maybe I can just make it work with both `.seq` and `.seq.seq` then? 

I guess that's in line with the robustness principle ("be conservative in what you do, be liberal in what you accept from others"), even if we can't support every possible way people rename their files. I guess in the long run, #807 is the correct way to fix this.
