### ISSUE TITLE
codecov.io: migrate to new uploader

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#1190]
The old bash-based uploader is sadly being replaced, so we will need to migrate to their new one: https://docs.codecov.com/docs/codecov-uploader

At the same time, we can work on improving the config, like [only notifying after N builds have completed](https://docs.codecov.com/docs/notifications#section-preventing-notifications-until-after-n-builds) to get rid of the "wrong" codecov comment in the beginning, which is later updated with a more correct comment. Most of the time, the numba-coverage-only runs finish first, and of course they don't cover the whole code base...

**Comment by matbryan52** [comment]
> At the same time, we can work on improving the config, like only notifying after N builds have completed to get rid of the "wrong" codecov comment in the beginning, which is later updated with a more correct comment. Most of the time, the numba-coverage-only runs finish first, and of course they don't cover the whole code base...

This is sorely needed ! Glad it's possible.
