### ISSUE TITLE
Implement fast ptychography

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#124]
Lots of people are interested in ptychography right now. We should add that capability to LiberTEM. Since it is our strength, we should aim towards a fast, parallel, distributed implementation. Here we can discuss the details.

**Comment by woozey** [comment]
As far as I understand ptychography in TEM is still not a fully developed method. It still faces quite critics from people with strong theoretical and practical background. It would still require numerous methodological developments and comparison of results with other phase techniques. On the other hand reconstruction algorithms can be made available with a disclaimer that result quality assessment and interpretation is up to users...

**Comment by uellue** [comment]
Closing here, see https://github.com/Ptychography-4-0/ptychography!
