### ISSUE TITLE
Use the architecture to simulate data

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#125]
Simulation and analysis goes hand in hand. We could integrate STEM simulation packages to generate data sets with very high throughput on the same cluster and cloud infrastructure that is used for storing and analyzing the acquired data.

**Comment by woozey** [comment]
I think providing interfaces would be the best. For example @fwin22 has been iteratively calling Dr.Probe from Python. My personal preference would be if LiberTEM will move towards acquisition as it was planned in the beginning...

**Comment by uellue** [comment]
This is now possible by creating a Dask array from a UDF result and applying the UDF to a parameter map, for example.
