### ISSUE TITLE
Conda-Forge packaging

### ISSUE THREAD

**Issue by matbryan52** [LiberTEM/LiberTEM#1271]
Looking into packaging via condaforge, it seems we're all good to go except for two things:

- we depend on https://pypi.org/project/empyre/ which is also not distributed though conda-forge (or conda). According to the doc this is problematic  (see this FAQ entry, for example: https://github.com/conda-forge/staged-recipes#6-do-all-of-my-packages-dependencies-have-to-be-in-conda-forge-already ). As it is a Jülich project you could possibly publish empyre to conda-forge, otherwise we would have to port the code into LiberTEM (or make empyre optional). See this Issue : https://github.com/conda/conda-build/issues/548
- [optional] we don't distribute the tests directory with the PyPi .tar.gz, which means `conda-build` can't run them when compiling the feedstock. This is not blocking as they admit that not all test suites are appropriate or possible - in our case they might be too slow to run anyway! - and we can specify anything as tests including just a simple import or a short test script.

I've set up the recipe / fork / branch here as a project repo: https://github.com/LiberTEM/condaforge-staged-recipes/tree/libertem/recipes/libertem, next step would be to make a PR onto the parent repo for this branch, wait for it to be reviewed and then merged, and we're live.

Other notes:

- I've set @uellue @sk1p and myself as maintainers in the recipe, which should mean we are all able to handle updating the feedstock.
- There is a conda-forge bot which handles updating the feedstock when the PyPi version is updated. This generates a PR which we can then accept to push updates to the feedstock. If the dependencies of the package have changed then we need to update the PR with the new recipe, following the instructions here: https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests

**Comment by sk1p** [comment]
Thanks for looking into this!

> * we depend on https://pypi.org/project/empyre/ which is also not distributed though conda-forge (or conda). According to the doc this is problematic  (see this FAQ entry, for example: https://github.com/conda-forge/staged-recipes#6-do-all-of-my-packages-dependencies-have-to-be-in-conda-forge-already ). As it is a Jülich project you could possibly publish empyre to conda-forge, otherwise we would have to port the code into LiberTEM (or make empyre optional). See this Issue : [pip dependencies  in conda recipe conda/conda-build#548](https://github.com/conda/conda-build/issues/548)

I think it's even possible to publish something to conda as a third party, right? At least that's my mental model of conda, it is more similar to a Linux distribution than it is to just a package index. Nevertheless, we can make this happen.

/cc @jan-car 

> * [optional] we don't distribute the tests directory with the PyPi .tar.gz, which means `conda-build` can't run them when compiling the feedstock. This is not blocking as they admit that not all test suites are appropriate or possible - in our case they might be too slow to run anyway! - and we can specify anything as tests including just a simple import or a short test script.

Hm, yeah - we could think about changing that, to make sure the package really runs well with the versions available in coda. But I guess that would be a bit more work than just packaging LiberTEM itself. Maybe we can have a look at how other projects that use `tox` for testing handle this? Slowness may be an issue, but this only runs once (or twice) per release anyways, right?

**Comment by matbryan52** [comment]
> Thanks for looking into this!
> 
> > * we depend on https://pypi.org/project/empyre/ which is also not distributed though conda-forge (or conda). According to the doc this is problematic  (see this FAQ entry, for example: https://github.com/conda-forge/staged-recipes#6-do-all-of-my-packages-dependencies-have-to-be-in-conda-forge-already ). As it is a Jülich project you could possibly publish empyre to conda-forge, otherwise we would have to port the code into LiberTEM (or make empyre optional). See this Issue : [pip dependencies  in conda recipe conda/conda-build#548](https://github.com/conda/conda-build/issues/548)
> 
> I think it's even possible to publish something to conda as a third party, right? At least that's my mental model of conda, it is more similar to a Linux distribution than it is to just a package index. Nevertheless, we can make this happen.
> 
> /cc @jan-car

You're right, they specifically say anyone can submit a package https://conda-forge.org/docs/maintainer/maintainer_faq.html#mfaq-package-submit. In case we want to go that route I've made the recipe branch here: https://github.com/LiberTEM/condaforge-staged-recipes/blob/empyre/recipes/empyre/meta.yaml

> > * [optional] we don't distribute the tests directory with the PyPi .tar.gz, which means `conda-build` can't run them when compiling the feedstock. This is not blocking as they admit that not all test suites are appropriate or possible - in our case they might be too slow to run anyway! - and we can specify anything as tests including just a simple import or a short test script.
> 
> Hm, yeah - we could think about changing that, to make sure the package really runs well with the versions available in coda. But I guess that would be a bit more work than just packaging LiberTEM itself. Maybe we can have a look at how other projects that use `tox` for testing handle this? Slowness may be an issue, but this only runs once (or twice) per release anyways, right?

By slowness I just meant how much CI time they allocate to each package. It's probably fine.

I will see if I can locally setup tests with via the recipe. I think at a minimum we would have to add tests/, conftest.py, etc. to MANIFEST.in, then we specify the pytest entrypoint in the recipe and it should run.

**Comment by ReimarBauer** [comment]
Hi
Just coming back.

Have a look on grayskull when you need to add pypi packages to conda-forge. This simplifies creation of the recipe a lot.

Also if you want to create multiple packages from one feedstock I recently did this with basemap. That is just to know as an example.

Reimar

**Comment by matbryan52** [comment]
> Hi Just coming back.
> 
> Have a look on grayskull when you need to add pypi packages to conda-forge. This simplifies creation of the recipe a lot.
> 
> Also if you want to create multiple packages from one feedstock I recently did this with basemap. That is just to know as an example.
> 
> Reimar

The recipes in the fork I linked to were built using Grayskull, seems like a great tool. 

Creating a LiberTEM feedstock that provides Empyre also could be a possibility for the dependency, thanks for the advice I'll look into it.

**Comment by jan-car** [comment]
Thanks for the cc and sorry for the delayed response, I was ill the last week. If there's anything I can do to help on the Empyre side of things, just let me know.

**Comment by matbryan52** [comment]
Hi @jan-car , no worries.

Where we're at:   there is a branch `libertem_empyre` here https://github.com/LiberTEM/condaforge-staged-recipes/tree/libertem_empyre :

in which there is a recipe for empyre:

- https://github.com/LiberTEM/condaforge-staged-recipes/blob/libertem_empyre/recipes/empyre/meta.yaml

and one for libertem:

- https://github.com/LiberTEM/condaforge-staged-recipes/blob/libertem_empyre/recipes/libertem/meta.yaml

which currently points to a temporary .tar.gz built from current master (now that #1276 is merged). This combination of recipes passes the conda-build process including running the default libertem tests. When 0.10.0 is released we just need to adjust the source URL, check the dependencies, and re-run the test build before making the PR.

The one outstanding item I have is whether we want to run Empyre's tests when packaging. To do this would require distributing the tests directory with the source .tar.gz on PyPi (and re-releasing) ( [as with this PR](https://github.com/LiberTEM/LiberTEM/pull/1276/files#diff-41d5a52589e0480be9c099d2bba7a8135b8b0d71bcbb8df3582a8df1c2295003) )

**Comment by sk1p** [comment]
I had a quick look at the recipes, and they look good, as far as I can tell. One thing I wondered - why is there a `skip: true  # [py2k or py==39]`? This means the recipe isn't built on Python 2 and 3.9, correct? I think this is grayskull being confused by the explicit exclusion of the minor versions `3.9.{0,1,2}`, on which LiberTEM won't run properly. I don't think we can do this on conda at all, as the `py` preprocessor variable isn't set to the full version, but just the major version.

> There is a conda-forge bot which handles updating the feedstock when the PyPi version is updated. This generates a PR which we can then accept to push updates to the feedstock. If the dependencies of the package have changed then we need to update the PR with the new recipe, following the instructions here: https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests

For these PRs we should then probably have a short checklist of what things need to be ported from the pypi packaging (new dependencies, new console entry points, what else?) - these we could put into the main release check list. Or can we also update the recipes using grayskull? (stupid idea: just rebase our manual updates on top of the new auto-generated version?)

> The one outstanding item I have is whether we want to run Empyre's tests when packaging. To do this would require distributing the tests directory with the source .tar.gz on PyPi (and re-releasing) ( [as with this PR](https://github.com/LiberTEM/LiberTEM/pull/1276/files#diff-41d5a52589e0480be9c099d2bba7a8135b8b0d71bcbb8df3582a8df1c2295003) )

If you like, you can make a merge request for empyre to include the tests. You should be able to log in via your IFF account into iffgit and create a fork - please let me know if you need support with gitlab. Then either @jan-car or I can cut a release (Jan, let me know if you want to handle this - I _think_ I can manage without messing up :grin: ). We could then go ahead and create the PR for the empyre feedstock, even before the LiberTEM 0.10 release.

**Comment by matbryan52** [comment]
> I had a quick look at the recipes, and they look good, as far as I can tell. One thing I wondered - why is there a `skip: true # [py2k or py==39]`? This means the recipe isn't built on Python 2 and 3.9, correct? I think this is grayskull being confused by the explicit exclusion of the minor versions `3.9.{0,1,2}`, on which LiberTEM won't run properly. I don't think we can do this on conda at all, as the `py` preprocessor variable isn't set to the full version, but just the major version.

Good spot! I've remove the `py==39` but left the `py2k` (I don't think it would run anyway ?). Confirmed tests run on py39.

> For these PRs we should then probably have a short checklist of what things need to be ported from the pypi packaging (new dependencies, new console entry points, what else?) - these we could put into the main release check list. Or can we also update the recipes using grayskull? (stupid idea: just rebase our manual updates on top of the new auto-generated version?)

Agreed, I will try to write this and I suppose it should be added to the standard release checklist.

> If you like, you can make a merge request for empyre to include the tests. You should be able to log in via your IFF account into iffgit and create a fork - please let me know if you need support with gitlab. Then either @jan-car or I can cut a release (Jan, let me know if you want to handle this - I _think_ I can manage without messing up grin ). We could then go ahead and create the PR for the empyre feedstock, even before the LiberTEM 0.10 release.

I've created the fork, added the tests, and also fixed what I think is a bug in `__array_ufunc__` which was causing a bunch of tests to fail. Specifically when the `out=` kwarg to the ufunc was `(None,)` numpy was raising a `TypeError`. I've added a line which converts the single-entry `(None,)` to just `None` and now no problems (with the tests). [Mixed/mutil-array `out=` or single-array out will still remain as they are.]

MR is here: https://iffgit.fz-juelich.de/empyre/empyre/-/merge_requests/40/diffs

The joint (and invidual Empyre) conda recipes are now passing, there is an `empyre` branch in that recipe repo pointing to a temporary release tarball for testing.

**Remaining item on my list** - Empyre's requirements aren't super clearly specified (there is an environment.yaml which mixes tests, build etc). I am worried that the recipe doesn't include something critical not covered by the tests (notably hyperspy or pyFFTW). Could someone who knows the code comment on that ??

**Comment by ReimarBauer** [comment]
you don't need to skip py2k because it is not possible to build easily for py2k. It is not in the defaults.

https://conda-forge.org/docs/user/announcements.html#python-2-7-admin-command-available

**Comment by ReimarBauer** [comment]
I'm not looked in detail how you use/create your test package. Please have a look on the discussion there https://github.com/cedadev/nappy/issues/59
 
In a package usually you don't have tests and the libs to ran these tests as additional dependency.

**Comment by jan-car** [comment]
I'll have a look at the MR in the evening and also check the requirements, so we can create an empyre release with the changes 👍.

**Comment by sk1p** [comment]
> In a package usually you don't have tests

Can you clarify? Do you mean the sdist doesn't include tests? What are then the logistics of running them in the conda build process?

In our (libertem) case, the sdist does include the tests, meaning we can run them in the conda package, but they do not get installed by pip, and are not part of the wheel.

**Comment by matbryan52** [comment]
> I'm not looked in detail how you use/create your test package. Please have a look on the discussion there [cedadev/nappy#59](https://github.com/cedadev/nappy/issues/59)
> 
> In a package usually you don't have tests and the libs to ran these tests as additional dependency.

LiberTEM and Empyre have similar structures, the `tests/` directory is outside of the package tree and is run with `pytest` via a `conftest.py`. At least for LiberTEM the test_requirements are separate to the package requirements and so are not installed via pip. This should be the same for the conda recipe as the test-only requirements (pytest + plugins, notably) are under the test: part of the recipe and as such are only required during the build process.

Given the recipe build command (`python -m pip install . -vv`) and the config of the `setup.py`, I don't think the tests will be installed as a package (as they are not installed currently when running from PyPi or directly from a local pip install).

**Comment by jan-car** [comment]
@matbryan52 , I tried to merge your changes, but I'm running into a few problems (I haven't been in the repo for quite some time, so it seems there's a lot of cleanup to be done).
![image](https://user-images.githubusercontent.com/14233291/176793552-83e5f067-7998-40a6-b2d8-ffb39e5e9c0a.png)

First, I couldn't merge due to the pipeline check being stuck in the loading animation, which might make sense, because no MR pipeline ran, at all.
Apparently, this is not turned on by default (see https://docs.gitlab.com/ee/ci/pipelines/merge_request_pipelines.html), so I added the according section in the `gitlab-ci.yml` file.
I tried to rebase the branch, but got the error message above (I thought, that maybe I need permission to access https://iffgit.fz-juelich.de/bryan/empyre/-/tree/conda_packaging, it gives me a 404).

As a sanity check, I tried to run the normal pipeline simply on master (because the last one ran 1 year ago), but that failed as well... I'll have another look tomorrow, when I find the time, maybe @sk1p can have a quick look as well 🙂?

> Remaining item on my list - Empyre's requirements aren't super clearly specified (there is an environment.yaml which mixes tests, build, etc.). I am worried that the recipe doesn't include something critical not covered by the tests (notably hyperspy or pyFFTW). Could someone who knows the code comment on that ??

There are two places where the requirements are specified (I know, not best practice, but I did that during my thesis, when I was not as experienced 😅).
- The `environment.yml` was mainly used by me to quickly setup an environment with everything I needed to work with the package. That also includes stuff like Jupyter notebooks and similar things that are not required for Empyre, but were simply there for quality of life to quickly get going. However, most tests use conda to prepare exactly this (bloated) environment, which you can see in the `before_script` in the `.gitlab-ci.yml`. All tests that go this routes currently fail in the pipeline!
- The "true" requirements are located in `settings.cfg`, here, with additional/optional dependencies clearly separated in the `[options.extras_require]` section (which also means that `hyperspy` and `pyFFTW` will indeed not be installed by default, only if you specify it, or by using `pip install empyre[all]`. The only test job that goes that route is the `test_install` job, which is the only one that actually succeeds.
![image](https://user-images.githubusercontent.com/14233291/176794974-37c6eb22-a0b3-4c57-9cc7-7cfa2ac93281.png)

Hope that clears some things up and sorry that I couldn't merge, yet, I got a bit rusty with my own repo, it seems...

**Comment by matbryan52** [comment]
Hi @jan-car thanks for taking a look, and sorry for the delay I was away this weekend.

So I've took a look at GH and I've rebased my MR on top of your change so that should no longer be a problem.

In debugging the CI I think the pipeline fails in the `before_script` step when creating the conda environment (`conda env create -q`) which reads your `environment.yml` file. The issue is maybe linked to the fact that all the package versions are pinned, the size of the environment, or the channel priority setting (I am not a conda expert). Essentially, solving the environment is taking a **really** long time (both in the pipeline and when I tested it locally inside a container), and I think the CI might be just giving up. I played around with it but I cannot find a satisfactory solution using conda.

One option might be to figure out which are the minimal requirements for the package (and unpin their versions) and also those for testing, then directly install them using pip or conda in the CI, rather than as one big environment definition. (For example I could manually install `numpy scipy scikit-image` in a few seconds, but the environment.yml install hangs for 10+ minutes).

**Comment by sk1p** [comment]
(just a side node: there is an alternative dependency solver being worked on that is supposedly quite a lot faster: https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community )

**Comment by matbryan52** [comment]
> (just a side node: there is an alternative dependency solver being worked on that is supposedly quite a lot faster: https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community )

Just gave it a try, still slow with this environment.

For now I've fixed by switching to a `pip install .[tests]` and manually installing the docs requirements in the pipeline. The CI is passing for the repo/MR now.

**Comment by matbryan52** [comment]
Closed with https://github.com/conda-forge/staged-recipes/pull/19861
