### ISSUE TITLE
__pycache__ and *.pyc included in (PyPi) source tarball

### ISSUE THREAD

**Issue by matbryan52** [LiberTEM/LiberTEM#1275]
While looking into #1271 I think I've found that the PyPi .tar.gz (and probably also the .whl) contain all the .pyc files.

from https://files.pythonhosted.org/packages/17/a4/20eb6a06158774138afbd4118e2800d1e0db54fd5a8136025cd723535ee3/libertem-0.9.2.tar.gz

![image](https://user-images.githubusercontent.com/78845903/175030180-f8816450-ff1a-4fdf-a096-8a693e2bb4e1.png)

From my understanding .pyc is OS+Python version specific so I think this just inflates the bundle size?

I can reproduce this when running `python -m build` and `python setup.py sdist` locally.

**Comment by sk1p** [comment]
> From my understanding .pyc is OS+Python version specific so I think this just inflates the bundle size?

Yeah, agreed.

Something like this should fix the issue, although I haven't checked if this still includes everything important:

```patch
diff --git a/MANIFEST.in b/MANIFEST.in
index ab29f94f..1260f363 100644
--- a/MANIFEST.in
+++ b/MANIFEST.in
@@ -1,7 +1,8 @@
-graft src
+graft src/libertem/web/client/
 include LICENSE
 include README.rst
 graft client
 prune client/node_modules
 prune client/build
 prune client/coverage
+global-exclude *.pyc __pycache__
```

Still includes the built client, such that people don't need to build the client if they just install from sdist.
