### ISSUE TITLE
UDFKwargsWrapper.get (self.params.get) fails for missing keys

### ISSUE THREAD

**Issue by matbryan52** [LiberTEM/LiberTEM#1284]
`UDFKwargsWrapper`, which is used for `udf.params`, inherits from `UDFData`. As a consequence the `.get(key, default)` method calls `UDFData.__getattr__(key)` which raises `AttributeError` if the key is missing. However, the `.get` method was written as such:

```python
def get(
    self, k: str, default: Optional[T] = None
) -> Optional[Union[T, np.ndarray, BufferWrapper]]:
    try:
        return self.__getattr__(k)
    except KeyError:
        return default
```
as a result I don't think it's possible to actually ever return `default` from `.get(key, default)`.

Clearly a simple fix, but given the highly connected nature of the code (used for Buffers, Results, Aux data, udf.params...) before pushing I wanted to ask if this behavior was intentional (i.e the default value is actually inaccessible) to enable something else in the codebase?

**Comment by sk1p** [comment]
This looks like an oversight, good catch! That method [doesn't have test coverage](https://app.codecov.io/gh/LiberTEM/LiberTEM/blob/master/src/libertem/udf/base.py), so at least in LiberTEM nothing should depend on that behavior.
