### ISSUE TITLE
Guess a square nav_shape if a square number of frames detected in the web interface

### ISSUE THREAD

**Issue by matbryan52** [LiberTEM/LiberTEM#1309]
For datasets which define their sig shape but not their nav shape (e.g. non-integrated Merlin), if a square number of frames is detected we could guess a square scan grid given how common that choice is in reality.

**Comment by matbryan52** [comment]
Looking at the various datasets, I can see the cases where we fall back to `nav_shape = (image_count,)` in `detect_params` are the following:

- MIB
- TVIPS
- SEQ
- MRC
- K2IS

A small util function Python-side could be applied to these fall-back cases, giving a square nav shape if image_count is a square. This would avoid having to handle this on the Typescript side.

**Comment by sk1p** [comment]
> A small util function Python-side could be applied to these fall-back cases, giving a square nav shape if image_count is a square. This would avoid having to handle this on the Typescript side.

Sounds good to me!
