### ISSUE TITLE
Averaged preview image depends on partition shape with .blo file

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#132]
I was experimenting with the "Tileshape" parameter while loading the Glasgow BaTiO3 / BiFeO3 .blo data set.

Observed behavior: The averaged preview image on the left depends on the first two items of the "Tileshape" setting.

Expected behavior: The averaged preview image is the same, independent of tileshape.

Examples:
(90,121,144,144)

![image](https://user-images.githubusercontent.com/25689052/46339638-a2195100-c633-11e8-84de-959c541e7e26.png)

(1,8,144,144)

![image](https://user-images.githubusercontent.com/25689052/46339684-bfe6b600-c633-11e8-8642-dd27ec19c26c.png)

(8,121,144,144)

![image](https://user-images.githubusercontent.com/25689052/46339720-d725a380-c633-11e8-8846-a2ee9eb0f6ba.png)

(8,70,144,144)

![image](https://user-images.githubusercontent.com/25689052/46339796-04725180-c634-11e8-9d17-9304c6218928.png)

(8,8,144,144)

![image](https://user-images.githubusercontent.com/25689052/46339837-1bb13f00-c634-11e8-8bd3-2168cd5e265b.png)

(90,8,144,144)

![image](https://user-images.githubusercontent.com/25689052/46339899-3e435800-c634-11e8-8a33-a7ffa66ed405.png)

(90,121,12,12) -- same as (90,121,144,144)

![image](https://user-images.githubusercontent.com/25689052/46340085-b7db4600-c634-11e8-84f8-26cfc614b80a.png)

**Comment by uellue** [comment]
Looking at the data set, it seems that only an average of the first partition is taken. That explains why the very prominent (110) reflections  of the central region are only present in images with a large partition size. With small partitions, only an average of a border region is taken that doesn't contain the prominent (110) reflections.

**Comment by sk1p** [comment]
This should now be fixed in master, but leaving this still open as I still need to write a test for it.

**Comment by uellue** [comment]
@sk1p Thank you! Works for me now. :-)

**Comment by sk1p** [comment]
Hm, the test works for me locally but fails in CI: https://travis-ci.org/LiberTEM/LiberTEM/jobs/437113763 - need to investigate.

**Comment by sk1p** [comment]
Should be fixed, was missing a commit when cherry picking.
