### ISSUE TITLE
Issue with file opening in new version

### ISSUE THREAD

**Issue by kruzaeva** [LiberTEM/LiberTEM#133]
Impossible to open files with dot '.' in their name, (ex. 'filename1.1 .blo')

**Comment by uellue** [comment]
To be precise, the opening dialog refuses to switch the file type from RAW to, for example, BLO, which makes opening the file impossible. The bug wasn't present in previous versions and only occurred after updating to the master branch today.

**Comment by sk1p** [comment]
This should now be fixed as of 7dda088f9a5635c24a119f69af3f14767d1d8279 (ts rebuilt in dfbfcb23fd28346d886acacab79b89b0c560293d), can you re-test please?

**Comment by sk1p** [comment]
Verified as fixed.
