### ISSUE TITLE
`io.dataset.detect()` first try the dataset type matching the file extension, if possible

### ISSUE THREAD

**Issue by matbryan52** [LiberTEM/LiberTEM#1370]
In `io.dataset.detect()` we infer the dataset type by iterating over the `filetypes` dictionary  until `cls.detect_params` doesn't raise for that particular definition.

We could instead prioritize the dataset which matches the file extension, if such a match is possible, which would save time when using `ctx.load('auto')` and also when detecting a dataset in the web GUI. 

This could be made to support datasets which have multiple file types, and also one file extension matching multiple dataset types, if at runtime we generate the possible matches to search first, and then fall back to the current behaviour if these don't exist and/or fail.

**Comment by sk1p** [comment]
> One caveat is the fact that the `detect` function uses delayed imports of the DataSet classes, so we don't have the definitions of all the supported file types (these are currently defined on the datasets themselves in `get_supported_extensions`).

True - probably there's still a win of only doing the imports and collecting file extensions vs. calling all those `detect` functions
