### ISSUE TITLE
The GUI should handle an exception during processing more gracefully

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#140]
When bug #138 is triggered, the GUI shows an eternal spinner. The waiting can be terminated by re-adjusting the ROI so that #138 is not triggered and clicking "Apply".

What I'd expect to happen:
If a job causes an exception and terminates prematurely, the GUI shows a helpful error message.

**Comment by sk1p** [comment]
This is now fixed. For the asynchronous job processing we are doing, we explicitly need to send an error message over the websocket in these cases, and appropriately handle those in the GUI, which is now implemented.

**Comment by uellue** [comment]
Great! I can't test it because I don't know an exception that I can trigger with the current version. I guess that's a good sign! :-D
