### ISSUE TITLE
Notebook progress bar still in stderr if no `ipywidgets`

### ISSUE THREAD

**Issue by matbryan52** [LiberTEM/LiberTEM#1417]
We get a warning when running with `progress=True` in a notebook on a clean install. This originates from Tqdm because we don't require `ipywidgets` as part of a LiberTEM install. It isn't breaking (the bar still works like it did before), but is a little unfortunate.

```stderr
~/.pyenv/versions/3.10.9/envs/lt_rc/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Partitions 32/32, Frames: 100%|█████| 66402/66402 [00:07<00:00, 8674.72it/s]
```

**Comment by sk1p** [comment]
We now depend on `ipympl`, which depends on `ipywidgets`, so this should no longer be an issue
