### ISSUE TITLE
Configure `libertem-server` worker params from command line

### ISSUE THREAD

**Issue by matbryan52** [LiberTEM/LiberTEM#1419]
Right now we require the user to go through a create/connect page before loading data in `libertem-server`.

I would argue that in most cases people immediately click 'Connect' without looking at the content. We could offer the ability to pre-configure the cluster from the launch command, e.g.:

```bash
libertem-server -c 8 -g 1
```

which would create an 8 cpu / 1 gpu cluster and put you immediately on the select data file browser page. It might even be worth it to just create a maximum-resource cluster by default, and the current behaviour with the configuration page  becomes an option, too (which is already what we do with a simple call to `lt.Context()`).

This could also extend to connecting to existing Dask clusters:

```bash
libertem-server --dask-scheduler 100.100.100.100:8080
```

The goal would to reduce the typical time-to-analysis. If implemented in a certain way the cluster could still be loading / preloading at the same time the file browser page is loading in and becomes ready to use.

**Comment by matbryan52** [comment]
An additional feature here would be to actually expose the scheduler address when `libertem-server` creates a cluster, that way you have a one-command solution to set up a LiberTEM-configured cluster on a server somewhere, then connect to it remotely from another machine.

**Comment by sk1p** [comment]
Agreed - defaulting to a max resource cluster is a good idea. We could then have a "reconfigure cluster" command in the status bar, to add/remove workers (which would in reality stand up a new cluster when applying).

With #1353 we should also have better defaults for the number of CUDA workers (and maybe detection of pinning via `taskset` or constrained docker CPU resources?), meaning one less reason to change the defaults.
