### ISSUE TITLE
Preloading / Unloading workers can take a long time on huge systems + stderr spam

### ISSUE THREAD

**Issue by matbryan52** [LiberTEM/LiberTEM#1420]
This is possibly an upstream issue, but creating our cluster and tearing it down (particularly in the case of a crash) can take a really long time of a machine with many cores. In my case on a 64 core machine the web interface can become responsive for a long time while the cluster preloads.

In addition the preload `stderr` spam can be extensive, which I think we could better configure for our usecase even if it's the upstream default.

**Comment by uellue** [comment]
Maybe useful? https://distributed.dask.org/en/stable/logging.html
