### ISSUE TITLE
Move grid matching code out of core LiberTEM?

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#1469]
The `gridmatching` (or more specifically, the `fullmatch`) code is the only place we depend on `hdbscan`. We have had a bunch of compatibility issues in the past, and it would be nice if normal LiberTEM development was not interrupted by those issues, and to rather contain the blast radius of such issues.

Should we move this code (including tests and examples) to another repository; maybe to `LiberTEM-blobfinder`?

**Comment by sk1p** [comment]
@uellue @matbryan52 discussed today in the call

**Comment by sk1p** [comment]
To elaborate, in addition to the mentioned compatibility issues, `hdbscan` also slows down our CI, as they don't publish wheels. `time pip install hdbscan` in a clean environment (and removing my local cached built wheel) takes ~30s, this is probably even slower on most of the CI runners.

**Comment by uellue** [comment]
Currently working on a PR to move the code to Blobfinder. Looking good so far, checking docs etc.
