### ISSUE TITLE
Notebook export bug (from upstream `autopep8`)

### ISSUE THREAD

**Issue by matbryan52** [LiberTEM/LiberTEM#1490]
We're affected by this issue in `autopep8` when exporting a notebook:

https://github.com/hhatto/autopep8/issues/689

specifically in:
 
```
  File "D:\...\envs\lt_release012\Lib\site-packages\libertem\web\notebook_generator\template.py", line 36, in code_formatter
    return autopep8.fix_code(code)
           ^^^^^^^^^^^^^^^^^^^^^^^
```

From activity on the issue it looks like it will soon be handled ?

#1476

**Comment by matbryan52** [comment]
Seems like a solution is to pin `pycodestyle` to 2.10.0.

**Comment by sk1p** [comment]
> Seems like a temporary solution is to pin `pycodestyle` to 2.10.0

Yeah, probably `<2.11` is the correct pin, to not be overly strict

**Comment by sk1p** [comment]
I'll take care of this one - theoretically the notebook tests should also reproduce the issue, I'll see if that is the case
