### ISSUE TITLE
Documentation for the file formats

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#156]
Write detailed documentation on how to open the various supported formats. Should be done after improving usability of opening files #65. Related to #86.

- [x] MIB #129 
- [x] RAW (different variants, including endian-ness #144)
- [x] HDF5
- [x] BLO 
- [x] K2IS #63 #109 
- [x] FRMS6  #155
- [ ] MRC #152 
- [ ] Norpix Seq #153 
- [x] TIA SER/EMI
- [x] EMPAD

**Comment by sk1p** [comment]
I've started working on this, see https://libertem.github.io/LiberTEM/formats.html in a few minutes. Let me know what you think about this style of docs. For some formats, in addition to the docstring, we may need a paragraph about differences to the GUI (for example, the GUI cannot specify the gain map for FRMS6 data sets yet)

**Comment by sk1p** [comment]
As we have neither MRC nor Norpix Seq support yet, I'll close this for now. New file formats should be directly added to the docs.
