### ISSUE TITLE
Switch computational backend to 2D/3D partitions / tiles

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#157]
* support for vector scans / spectral data
 * general support for time/tilt/... series
 * some file formats are inherently 3D in shape (that is, stacks of frames) which makes the mapping file <-> 4D partition awkward
 * keep 4D info in metadata

**Comment by sk1p** [comment]
See also: #99

**Comment by uellue** [comment]
I guess #195 closes this for the back-end?
