### ISSUE TITLE
Incorrect MIME type guessing breaks web GUI

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#1612]
This is an issue that Windows use can hit, where the symptom is the LiberTEM GUI just being blank, and an error about incorrect mime type, something like this: "Failed to load module script: The server responded with a non-JavaScript MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec."

The cause is the `mimetypes` module, that's part of the Python standard library, detecting the wrong MIME type, because of an invalid registry entry: https://github.com/python/cpython/issues/88141

I think we can work around this issue by using `mimetypes.add_type(type, ext)` to override the internal type.

**Comment by matbryan52** [comment]
Honestly amazed that you were able to track this down, well done !
