### ISSUE TITLE
Support for malformed EMPAD files

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#1617]
The files in https://er-c-data-mgmt.fz-juelich.de/browse/?path=/adhoc/libertem/libertem-test-data/EMPAD/Magical_DataSet#browse don't work with with current EMPAD reader as deployed on moellenstedt.

**Comment by sk1p** [comment]
Loading via `ctx.load("empad", ...)` gives:

```
[...]
File ~/source/LiberTEM/src/libertem/io/dataset/base/file.py:166, in get_array_from_memview()
    162 assert len(mem) % itemsize == 0, \
    163     "len(mem) must fit the dtype"
    164 assert len(mem) // itemsize % self.num_frames == 0, \
    165     "len(mem) must fit the number of frames"
--> 166 assert len(mem) // itemsize // self.num_frames % (
    167     slicing.frame_size + (self._frame_header + self._frame_footer) // itemsize
    168 ) == 0, "len(mem) must fit the sig shape"
    169 arr_uncut = np.frombuffer(mem, dtype=self._native_dtype).reshape(
    170     (self.num_frames, -1)
    171 )
    172 arr = arr_uncut[:, slicing.frame_offset:slicing.frame_offset + slicing.frame_size]

AssertionError: len(mem) must fit the sig shape
```

Probable cause: the raw file has shape `(128, 16)`, and the XML file contains the following:

```
  <scan_parameters mode="search">
    <scan_resolution_x>16</scan_resolution_x>
    <scan_resolution_y>128</scan_resolution_y>
    <scan_center_x>0.5</scan_center_x>
    <scan_size>1.0</scan_size>
    <scan_center_y>0.5</scan_center_y>
  </scan_parameters>
  <scan_parameters mode="acquire">
    <scan_resolution_x>256</scan_resolution_x>
    <scan_resolution_y>256</scan_resolution_y>
    <scan_center_x>0.5</scan_center_x>
    <scan_size>1.0</scan_size>
    <scan_center_y>0.5</scan_center_y>
  </scan_parameters>
```

So the `mode="search"` parameters are actually the correct ones. I'll try to track down how this happens, and we should probably inform TFS about this - but now there are these kind of files around. As a work around for this, we could match the file size with the different scan parameters and select the one that matches.

**Comment by uellue** [comment]
If we have an enumerable number of options we can perhaps check which ones match the actual raw data file size?

**Comment by uellue** [comment]
> If we have an enumerable number of options we can perhaps check which ones match the actual raw data file size?

:-D I should have read your comment before more carefully: 

>  As a work around for this, we could match the file size with the different scan parameters and select the one that matches.

**Comment by sk1p** [comment]
> we should probably inform TFS about this

Internally, we have opened a support case for this issue, as it is definitely happening at our Spectra microscope.
