### ISSUE TITLE
Keyboard interaction for frame picking

### ISSUE THREAD

**Issue by FWin22** [LiberTEM/LiberTEM#164]
It would be useful to enable a movement of the frame picker by the keyboard arrows.
In addition, it would be good if the coordiantes of the frame picker are displayed.
@sk1p

**Comment by uellue** [comment]
@FWin22 the coordinates of the frame picker are displayed under the detector frame window. Probably they should be displayed under the scan image instead.

**Comment by FWin22** [comment]
That would help @uellue
