### ISSUE TITLE
`DeprecationWarning` from `empyre`

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#1652]
> ../../miniconda/envs/libertem/lib/python3.12/site-packages/empyre/fields/field.py:13: 26 warnings
  /home/alex/miniconda/envs/libertem/lib/python3.12/site-packages/empyre/fields/field.py:13: DeprecationWarning: numpy.core is deprecated and has been renamed to numpy._core. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.numeric.
    from numpy.core import numeric

**Comment by matbryan52** [comment]
Handled here : https://iffgit.fz-juelich.de/empyre/empyre/-/merge_requests/48
