### ISSUE TITLE
v0.14.1 point release

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#1657]
Issues/PRs that should be included:

-  #1656
-  #1660

@uellue @matbryan52 would any of you like to take charge of this release?

# Release checklist

Issues and pull requests to be considered for this release:

-  #1656

## Step 0: before cutting the release candidate

* [x] Document point release with version downgrade, while we are at it.
* [x] Review open issues and pull requests
* [x] Confirm that pull requests and issues are handled as intended, i.e. milestoned and merged
      in appropriate branch.
* [N/A] License review: no import of GPL code from MIT code
      `pydeps --only "libertem" --show-deps --noshow src\libertem | python scripts\licensecheck.py`
* [x] Run full CI pipeline, including slow tests, on [Azure DevOps](https://dev.azure.com/LiberTEM/LiberTEM/_build?definitionId=3) and run the [Thorough workflow](https://github.com/LiberTEM/LiberTEM/actions/workflows/thorough.yml) on GitHub Actions
* [N/A] Handle deprecation, search the code base for `DeprecationWarning`
      that are supposed to be removed in that release.
* [N/A] GUI dependency update with `npm install`
* [N/A] Review https://github.com/LiberTEM/LiberTEM/security/dependabot and update dependencies
* [N/A] Full documentation review and update, including link check using
      ``sphinx-build -b linkcheck "docs/source" "docs/build/html"``
* [x] Update the expected version in notes on changes, i.e. from `0.3.0.dev0`
      to `0.3.0` when releasing version 0.3.0.
* [x] Update and review change log in `docs/source/changelog.rst`, merging
      snippets in `docs/source/changelog/*/` as appropriate.
* [N/A] Edit `pytest.ini` to exclude flaky tests temporarily from release
      builds, if there are currently any flaky tests
* [N/A] Update the JSON files in the ``packaging/`` folder with author and project information

## Step 1

* [x] Create a release candidate using `scripts/release`. See
      `scripts/release --help` for details. Example command:
      `./scripts/release bump v0.3.0rc1 --tag`, then push to GitHub
* [x] Confirm that wheel, tar.gz, and AppImage are built for the release candidate on
      [GitHub](https://github.com/LiberTEM/LiberTEM/releases)
* [x] Confirm that a new version with the most recent release candidate is created on
      [Zenodo.org](https://zenodo.org/doi/10.5281/zenodo.1477847) that is ready for submission.

## Step 2: using the release candidate package

* [fix any fallout after point release] Run tests for related packages w/ new LiberTEM version
    * [x] LiberTEM-live
    * [x] LiberTEM-holo
    * [ ] LiberTEM-blobfinder
    * [ ] ptychography40
    * [ ] LiberTEM-iCoM
* [x] Run complete test suite, including slow tests that are deactivated by default
      and tests that require sample files or CUDA support.
* [x] Install release candidate packages in a clean environment
      (for example:
      `python -m pip install 'libertem==0.2.0rc11'`)
* [x] Test the release candidate docker image
    * [x] Confirm rc images and tags on https://ghcr.io/libertem/libertem
* [x] Quick GUI QA: open in an incognito window to start from a clean slate
    * [x] Correct version info displayed in info dialogue?
    * [x] Run a couple of analyses to verify it is not entirely broken

## Step 3: bump version and let release pipeline run

* [x] Final version bump: `./scripts/release bump v0.3.0 --tag`, push to github
* [x] After pipeline finishes, write minimal release notes for the [release](https://github.com/liberTEM/LiberTEM/releases) and publish the GitHub release

## Step 4: after releasing on GitHub

* [x] Confirm that all release packages are built and release notes are up-to-date
* [x] Install release package
* [x] Confirm correct version info
* [x] Confirm package upload to PyPI
* [x] Confirm images and tags on https://ghcr.io/libertem/libertem
* [x] Publish new version on zenodo.org
* [x] Update documentation with new links, if necessary
    * [x] Add zenodo badge for the new release to Changelog page
* [ ] Conda packaging: review PRs on https://github.com/conda-forge/libertem-feedstock/pulls
* [x] Send announcement message on mailing list
* [x] Edit `pytest.ini` to include flaky tests again
* [x] Bump version in master branch to next .dev0 (`./scripts/release bump v0.X.0.dev0 --commit`)
* [x] Add to institutional publication databases
* [skip] Add the current LiberTEM version to [CVL](https://github.com/Chasdfracterisation-Virtual-Laboratory/CharacterisationVL-Software>) - add both the singularity and the .desktop file!

**Comment by uellue** [comment]
@sk1p sorry to bother, but what were the steps for a point release again? Sth about setting the version by hand?

We didn't merge anything of importance since the last release, so no need for a stable branch.

**Comment by sk1p** [comment]
> @sk1p sorry to bother, but what were the steps for a point release again? Sth about setting the version by hand?

Yup, either setting the version to 0.14.1.dev0 by hand, or using the release script to "bump backwards" with `--force` (IIRC)

> We didn't merge anything of importance since the last release, so no need for a stable branch.

👍

**Comment by matbryan52** [comment]
> @uellue @matbryan52 would any of you like to take charge of this release?

I am happy to test and help but I haven't ever been close to the active part of release cutting before, would be coming from a ways behind. If @uellue you want to look at it together I am there.

**Comment by uellue** [comment]
Yes, `--force` made it downgrade. Thx! Now waiting for the thorough tests.

**Comment by uellue** [comment]
Cluster analysis doesn't like NumPy 2 on 3.9: https://github.com/LiberTEM/LiberTEM/actions/runs/9567900368/job/26376754929

--> #1658

**Comment by matbryan52** [comment]
> Cluster analysis doesn't like NumPy 2 on 3.9: https://github.com/LiberTEM/LiberTEM/actions/runs/9567900368/job/26376754929
> 
> --> #1658

Looks like the scikit-image release fixed the cluster analysis problem on py39 : https://github.com/LiberTEM/LiberTEM/actions/runs/9567900368/job/26404990589

**Comment by uellue** [comment]
I also confirmed that LiberTEM still works with NumPy < 2, since we recommend it. In a call until 11:00, then I will do short docs update.

**Comment by matbryan52** [comment]
Just a warning for now, I imagine this predates numpy2.

```
src\libertem\io\dataset\npy.py:11
  ~\Workspace\libertem_fork\src\libertem\io\dataset\npy.py:11: DeprecationWarning: `np.compat`, which was used during the Python 2 to 3 transition, is deprecated since 1.26.0, and will be removed
    from numpy.compat import long, asstr
 ```

**Comment by uellue** [comment]
> Just a warning for now, I imagine this predates numpy2.
> 
> ```
> src\libertem\io\dataset\npy.py:11
>   ~\Workspace\libertem_fork\src\libertem\io\dataset\npy.py:11: DeprecationWarning: `np.compat`, which was used during the Python 2 to 3 transition, is deprecated since 1.26.0, and will be removed
>     from numpy.compat import long, asstr
> ```

I'm preparing a PR to integrate the upstream changes which fix this. :-)

**Comment by matbryan52** [comment]
Think we're done with the point release ? Conda release is good, and we haven't seen any fires that I'm aware of
