### ISSUE TITLE
Better handle dask distributed errors

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#189]
Example: if you are running multiple jupyter notebooks, and they all start their own dask distributed local cluster, you may run into operating system limits when creating a `Context`, like number of file descriptors. Dask currently logs some generic error like "could not boot worker". We need to find a way to make this more user friendly!

**Comment by uellue** [comment]
Related to #200 ?

**Comment by uellue** [comment]
This hasn't been a real issue so far, I think. We did run into resource limits, but somehow always managed to diagnose the issue based on the error messages we received. Closing for now!
