### ISSUE TITLE
Clicking on a mask or pick control should give it keyboard focus

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#212]
This relates to the keyboard controls #164 .

Right now one has to click on the display _containing_ the marker to give keyboard focus to the selector, while clicking on the marker itself doesn't give it focus.

In the future, clicking on a marker should give it focus as well. That is particularly important if we want to support multiple markers within a window.

**Comment by sk1p** [comment]
Yeah, currently, only one handle can have focus - I basically delegate the keyboard stuff to the surrounding component. Should be possible to make this a per-handle thing.

**Comment by uellue** [comment]
Much easier to use keyboard now. 😄  👍
