### ISSUE TITLE
"Waiting" display when going from file browser to opening dialog.

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#215]
Executing dataset check routines on the cluster #205 has increased the latency of opening files in the GUI, in particular if the connection is slow. 

Right now, the file browser closes and shows an empty space with the "Browse" button on top. This persists long enough for users to suspect an error and click on "Browse" again.

Instead, we should communicate "work in progress", perhaps with "Checking <path>... " and a spinner.

**Comment by sk1p** [comment]
Done, now displays "Detecting parameters for {path}" message while busy.
