### ISSUE TITLE
Rename the ResultTile.copy_to_result() method

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#217]
The function name has mislead me to believe that it actually copies data, while in reality it adds the result. For that reason I didn't realize that the target has to be initialized.

Proposal: rename to "merge_into_result()"?

**Comment by uellue** [comment]
Or even better "reduce_into_result()"?

**Comment by sk1p** [comment]
`reduce_into_result` sounds good - in the same change I'd like to introduce a proper interface / base class for `ResultTile`, which is currently only duck-typed.
