### ISSUE TITLE
Event loop was unresponsive in Worker for 3.45s.

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#218]
When connecting to an existing dask cluster, the worker sometimes logs the following message:

```
distributed.core - INFO - Event loop was unresponsive in Worker for 3.43s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
```

This needs to be debugged and the root cause needs to be found.

**Comment by sk1p** [comment]
Observation: this appears to mostly happen for the first operation, maybe this is related to initially importing the required Python modules?

**Comment by uellue** [comment]
Yes, this sounds about right. If the workers are started by forking from a local process, they won't have to load modules.

**Comment by uellue** [comment]
I'll try the --preload option to see if that helps:

 http://distributed.dask.org/en/latest/setup.html#customizing-initialization

**Comment by uellue** [comment]
Fix confirmed with test on moellenstedt.
