### ISSUE TITLE
Include preloading in documentation

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#224]
Include info from #218 and #223 in documentation as soon as we describe using an external dask cluster.

**Comment by sk1p** [comment]
Maybe we should do preloading by default, I observed quite some delay on the first processing on the 18 core machine. In the best case with an indicator in the GUI that signals that the start up is not complete yet (but you can already open your data)?

**Comment by sk1p** [comment]
Hmm, somehow we forgot about this change - I'll assign it to the 0.4 milestone

**Comment by uellue** [comment]
This is partly documented in #1151. API documentation will be included in #1158.

**Comment by uellue** [comment]
...now in #1170!
