### ISSUE TITLE
libertem-server uses a lot of CPU time when processing MIB files

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#232]
How to reproduce:
Process the MOSFET strain MIB data set by Knut (MOSFET/20181119 185412/default1.mib) on moellenstedt with a disk analysis. It doesn't occur with the BiFeO3 RAW file of the same size.

Observed behavior: libertem-server is running at 100 % on one CPU for about 10 s. There's no reaction in the GUI or load from workers during that time. After that, the workers suddenly kick in and process the file in fractions of a second.

Expected behavior: The workers do most of the work and libertem-server is mostly busy collecting the results.

**Comment by sk1p** [comment]
I committed a potential fix in 1fc8d8861a08391a98409f766fa6b8735887ff98 that reduces the scope of data that is pickled and sent along with each task. Still not as fast as raw binary data, but much better than before.

**Comment by uellue** [comment]
@sk1p for disk analysis it works great now. However, for center of mass it still has the 10 s wait. Strange! I've confirmed that it doesn't happen for center of mass with the BiFeO3 raw data set.

**Comment by uellue** [comment]
@sk1p Update: The point analysis shows the same behavior.

**Comment by uellue** [comment]
@sk1p Update: Generating the preview sum image for K2IS (/data/users/clausen/02_0V_.gtg) pushes libertem-server to 110 % CPU on moellenstedt and takes a LONG time while the workers are practically idle.  A disk, point, ring or COM analysis is done in  seconds on that data set and puts load on the workers, not the server. This happens in a situation where the file should be in the file system cache, i.e. after several fast runs with the fast-running analyses.

Maybe this is related?

**Comment by sk1p** [comment]
This should now be fixed. There were still some indirect references to the `DataSet`, because the mask factories closed over 'self' (the analysis instance), which in turn has a reference to the dataset.

**Comment by uellue** [comment]
Fix confirmed! 👍
