### ISSUE TITLE
Test docstring examples of API

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#236]
Discussion with @sk1p: Right now, we can't test the API docstrings because we don't have reference datasets available in the testing environment. #86 

As soon as #86 is fixed, we should test the docstrings automatically.

**Comment by sk1p** [comment]
Another possibility: move the memory dataset into `libertem.io` and implement something like `ctx.load("testdata")` which then can be used for examples and doc strings. Could be empty, random data, or even a single frame of real data, copied and shifted around for example notebooks.

**Comment by uellue** [comment]
@sk1p That sounds like an excellent solution.

**Comment by uellue** [comment]
Closing since this is implemented now. :-)
