### ISSUE TITLE
Client tests

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#240]
Discussion with @sk1p: commit 42a06ebbdecd8a106fc452de73b8c9f761d816d6 is an example for a regression that could be caught with automated tests of the client that run in isolation, in particular not needing a browser or a running API server with actual data.

We should add such tests for new features and for regressions. TODO items:

- [x] Include client tests in continuous integration
- [ ] Include instructions on running client tests in the documentation
- [x] Display client test coverage as a motivator like for the Python part.

**Comment by sk1p** [comment]
Working on this in #239 - I also noticed that coverage collection in travis wasn't working anymore, which I'll also fix.

Relevant links: 

 * https://facebook.github.io/create-react-app/docs/running-tests#travis-ci
 * https://facebook.github.io/create-react-app/docs/running-tests#coverage-reporting
 * https://github.com/codecov/example-node
