### ISSUE TITLE
Automatically determine tileshape

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#247]
The tileshape is one of the more confusing parameters currently when opening a dataset. We should verify that our current assumption (1MB tiles work well universally) is true, and when implementing #198, we should include variations over tileshape into the benchmark suite. It may be a good idea to still offer it as a tuning parameter, as different analyses may have different optimum tile sizes.

Many formats will get this for free from #322, with a stackheight set to fit 1MB. This of course only works for smaller frames, until #331 is fixed.

Format checklist:
- [ ] BLO
- [x] EMPAD (tileshape can't be set at all)
- [ ] HDF5
- [ ] K2IS (fixed to `(stackheight, 930, 16)`, need to automatically set stackheight)
- [x] MIB (tileshape optional, sets stackheight from tileshape)
- [x] RAW
- [x] SER

**Comment by sk1p** [comment]
Very much related: #554 - with that, we have a more centrally responsible module (`TileStream` and its subclasses) which takes care of tile sizes and should help close this issue.

**Comment by uellue** [comment]
Refs #706
