### ISSUE TITLE
Bad performance of MIB datasets reading

### ISSUE THREAD

**Issue by kruzaeva** [LiberTEM/LiberTEM#270]
Processing time for MIB dataset (8 GB, path="/cachedata/users/ruzaeva/34/01_ms1_10K.mib"), which is not split into small datasets, takes too long.
The reason is, probably, that data is not divided into partitions.

**Comment by sk1p** [comment]
Thanks for the report! Yes, this needs to change, and can be implemented similarly to the FRMS6 DataSet implementation. As there are actually quite some similarities between readers, this may be considered part of #252.

**Comment by sk1p** [comment]
This is now done in the `ds-refactor` branch, and will be merged soon.
