### ISSUE TITLE
Standard deviation map

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#273]
The standard deviation map in the frame view as used by @kruzaeva is a great tool to find interesting regions, for example peaks, as a complementary tool to the averaging view. The standard deviation map should be available for #272 as well to help find interesting regions for integration.

**Comment by sk1p** [comment]
See also #249

**Comment by sk1p** [comment]
This should actually now be quite easy to implement, as we have both integration of UDFs into the web API and stddev map implemented in #249. Any takers?

**Comment by uellue** [comment]
Closing since this is implemented already.
