### ISSUE TITLE
Implement fluctuation EM

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#276]
The calculation can be very fast and easy to implement. Basically, determine standard deviation in a masked region of each frame, if I understand correctly. 

https://pixstem.org/fem_analysis.html 
https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.78.1074

**Comment by sk1p** [comment]
FEM explainer: https://tem.msae.wisc.edu/fluctuation-microscopy/
