### ISSUE TITLE
Cropping/Culling

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#28]
There are two cases of cropping we should support:

- [x] 1) Cropping to the region of interest of the user, in the scanning dimensions
- [ ] 2) Automatic culling in the frame dimensions

For 1) I think it makes sense to wait until we have user demand and/or a user interface.

For 2) it makes sense to crop on two layers: computation and I/O. Once we have sub-frame tiling from #27 implemented, each tile can hold its bounding box and the I/O layer can check if we are interested in the data from this tile, before even reading the data. Example: bright field only needs data from the center of the frame, so we only read tiles whose bbox intersects with the bright field disk. In the computation layer, we can reduce the number of FLOPS we need to execute by tightly cropping the data (and mask) to the bbox of the bright field disk before executing the matrix multiplication.

**Comment by sk1p** [comment]
Cropping the scanning dimension is now supported, even though the implementations for each DataSet subclass are not as efficient yet as they could be.

**Comment by sk1p** [comment]
I should say: there is no user interface yet, only low level support. It is currently used by the frame picking implementation.

**Comment by uellue** [comment]
Closing since this has become pretty stale, apparently not a big issue. It might come up again with the "lazy slice" idea on file readers.
