### ISSUE TITLE
Spurious test failure

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#283]
See https://travis-ci.org/LiberTEM/LiberTEM/jobs/501225151 for details

**Comment by sk1p** [comment]
As we are using randomly generated inputs, we should seed the random generator, either with a static value (easy debugging) or with a new value for each run (possibly catches more bugs, like in this instance?)

For example, we can set the seed in a fixture like this:

```
rand.seed(0)
np.random.seed(0)
```

And log the seed to the console via [pytest live logging](https://docs.pytest.org/en/latest/logging.html#live-logs) in case of non-static seed.

**Comment by sk1p** [comment]
Sorry, hitting the rebuild button actually killed the old log. It was one of the mask application tests failing. I could not yet reproduce this locally.

**Comment by uellue** [comment]
Hm, that's an interesting one! Should we attribute it to cosmic rays for now, until it happens again and we find out how to reproduce it?

**Comment by sk1p** [comment]
I guess. If we find the time we can add the seed output as described above, so we can actually reproduce it the next time it happens :grin:
