### ISSUE TITLE
UDF: run functions in the cluster without reading an input dataset

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#288]
For example, to do some parallel post-processing on smaller result data, which can be potentially CPU-intensive. This can already be done "inline" if the processing only needs the result for a single frame; this new functionality would allow post-processing on the whole result.

The low-level functionality in executors [is already there](https://github.com/LiberTEM/LiberTEM/blob/fe9b1924c57e763a90fd8d1148888484c3f98ed2/src/libertem/executor/base.py#L19), but we need to provide a user-visible and -friendly API.

**Comment by uellue** [comment]
Maybe one can just create a Dask array from the result and use Dask for postprocessing? Closing!
