### ISSUE TITLE
Separate developer installation from regular installation

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#297]
Discussion with @sk1p: The difference between a developer setup and a regular installation has been a pitfall for novice users. We should move all content related to a developer setup to "Contributing" to keep the two tracks clearly separated.

**Comment by uellue** [comment]
@sk1p Is this still a current issue? Perhaps we can re-evaluate and test this with the next round of GSoC when we have to instruct students to set up for development?

**Comment by sk1p** [comment]
> Perhaps we can re-evaluate and test this with the next round of GSoC when we have to instruct students to set up for development?

:+1: I think this issue is a good candidate for a first PR from a GSoC student, especially if they had trouble following the docs

**Comment by Akhileshpm** [comment]
I would like to contribute.

**Comment by sk1p** [comment]
> I would like to contribute.

Hi, welcome to LiberTEM! Note that this issue may have some overlap with #598, so you may need to update your work once that PR is merged.

@Akhileshpm maybe you can get started by laying out a plan how the changes would look like - i.e. what you would move from the general installation docs to the "developer/contributor" installation guide.

**Comment by Akhileshpm** [comment]
okay,meanwhile i will contribute in other issue
