### ISSUE TITLE
UDF: detailed documentation

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#306]
Part of #286:

- [ ] move examples from usage to own page
- [ ] explain buffer kinds
- [ ] explain how the `make_buffers` function can create multiple buffers of different type and kind
- [ ] explain how the `init` function can create shared data, and that it is called multiple times (once per partition)
- [ ] create a diagram that explains the "mode of operation" - leave out architecture details and work on abstraction level "tasks executed by workers". include data flow and partitioning
- [ ] explain role and parameters of each function in detail, and explain what is gained by this interface compared to a simpler map-like interface without all the buffer handling etc.
- [ ] include a paragraph (or more likely: section) about efficiency, buffer re-use etc.

**Comment by jaewshin** [comment]
I will try to work on this

**Comment by uellue** [comment]
@sk1p @jaewshin Perhaps we could review what is still missing from the current documentation to close this issue?

**Comment by uellue** [comment]
The current state of UDF documentation should be fine for 0.2, probably? Closing now. We can create new issues for specific docs items when we become aware of them.
