### ISSUE TITLE
docs: conditional link checking

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#312]
As seen in #311, sometimes link checking the docs fails miserably for some reason. On non-docs related changes, this should not fail the build.

As noted on the PR:

> Only doing link checks on doc changes may work. Something like this:

```
if git diff $TRAVIS_COMMIT_RANGE --name-only | grep -q '^docs/'; then tox -e docs-linkcheck; fi
```

> We still need to build docs on all CI runs, as changes to doc strings in the code also need to be reflected in the documentation.

**Comment by uellue** [comment]
This is now solved with doing a manual link check as part of our release checklist, closing https://libertem.github.io/LiberTEM/releasing.html#before-using-a-release-candidate-package
