### ISSUE TITLE
Support for different data types on buffer

### ISSUE THREAD

**Issue by jaewshin** [LiberTEM/LiberTEM#315]
In the current implementation of bufferwrapper class, it is assumed that all the data stored in the buffer have the same types(or dimensions). For instance, if the data has (16, 16) dimension, then only data matrix of such dimension can be stored in the buffer. The class does provide extra_shape parameter, which allows us to add additional dimension to the data. However, this method assumes that we are adding data matrix of the same dimension (16, 16). This can easily lead to wasted space if, for instance, we want to store a single constant value in the buffer. Therefore, it would be nice to add support for storing different data types in the buffer.

**Comment by sk1p** [comment]
Thanks for filing the issue! Would the following API work for you? In the `make_buffers` function, for these single-value "buffers", you create a separate `BufferWrapper` instance with a new `kind="single"` parameter:

```
def make_buffers():
    return {
        'buf1': BufferWrapper(kind="sig", dtype="float32"),
        'buf2': BufferWrapper(kind="single", dtype="uint32"),
    }
```

In `fn` and `merge`, this "buffer" would be used just like any other. Does this look good? If you have a different suggestion, let me know.

About different data types in a single buffer: this is possible using structured numpy dtypes, but I'd like to keep it simple. If you want to have different dtypes (for example `float32` and `uint8`), I would suggest using different buffers.
