### ISSUE TITLE
Average of frames over ROI

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#32]
Ease of use: Select single frame with click in image, without clicking on extra button

**Comment by sk1p** [comment]
Should we actually defer the rest of this ticket (average over ROI) to 0.2?

**Comment by uellue** [comment]
Yes, I'd say so. 👍On Aug 8, 2018 15:53, Alexander Clausen <notifications@github.com> wrote:Should we actually defer the rest of this ticket (average over ROI) to 0.2?

**Comment by sk1p** [comment]
This is now implemented, starting with a disk-shaped ROI
