### ISSUE TITLE
Add citations to zenodo record (and docs)

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#320]
Our zenodo record should include citations, for example of papers describing any methods we implement.

Part of #82

**Comment by uellue** [comment]
Ideally, should read a BibTeX file since we already have a well-populated one from the book chapter.

**Comment by uellue** [comment]
For our documentation: https://build-me-the-docs-please.readthedocs.io/en/latest/Using_Sphinx/UsingBibTeXCitationsInSphinx.html
