### ISSUE TITLE
Implement subframe tiling for readers that use Partition3D

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#331]
- [ ] implement efficient cropped reading (at most read one contiguous block from each frame, then crop the requested area)
  - [ ] use efficient cropped reading for both `crop_to` and "subframe tiling"
- [ ] maybe share more of the low-level code (some readers could use a striding definition and could share most of the low-level reading code, I think?)

**Comment by uellue** [comment]
See also #554
