### ISSUE TITLE
TimeoutError in CI resolved by nannynanny()?

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#370]
The CI TimeoutError phenomenon hasn't occurred since we merged the PR #360 with nannynanny() waking up the loop regularly. Should we perhaps undo all the other changes, namely pinning dask.distributed to a lower version:
https://github.com/LiberTEM/LiberTEM/blob/8a93f7bc451637506a25b2466ad5ae51a08d5abb/setup.py#L136

and setting the thread count to one
https://github.com/LiberTEM/LiberTEM/blob/8a93f7bc451637506a25b2466ad5ae51a08d5abb/src/libertem/executor/base.py#L120

and see where that takes us?

**Comment by sk1p** [comment]
I would prefer to do that in 0.3 (or 0.2.1 or whatever we decide to release next)

**Comment by sk1p** [comment]
CI has been running smoothly for the last time, with exception of the time mocking anomaly, which should now be fixed.

**Comment by uellue** [comment]
What about the ThreadPoolExecutor? I'll do a PR to change it back, to see what that does.
