### ISSUE TITLE
Tiling in readers with potentially large frames

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#373]
Right now, only K2IS actually returns tiles, while other readers return frame stacks. The "magic 1 MB" is reached with only 4 frames for 256x256 float32 and a single 512x512 float32 frames.

What happens:
Many algorithms, namely dot product, benefit from depths in the region of 32 frames. We lose performance with very shallow frame stacks, in particular when combines with deep mask stacks.

What should happen:
We should support a tiling scheme with 1 MB tiles that contain data from about 32 frames for all formats that can have frame sizes of 256x256 or larger. That should make many operations significantly faster.

See also #27, #331, #247

**Comment by sk1p** [comment]
Moving this to 0.5, should be done after #198
