### ISSUE TITLE
'+' character in path name triggers "file not found" when opening on Windows

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#374]
How to reproduce:
Include a '+' character in the path name on Windows and open it in the file browser. A '+' only in the file name works!

What happens:
The file is shown normally in the file browser, but opening fails with a file not found error.

What should happen:
Any file with a valid name and path on the given platform works.

**Comment by sk1p** [comment]
Confirmed, same happens on Linux. I suspect it is missing URL encoding for the path somewhere, investigating...
