### ISSUE TITLE
CERN ROOT

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#4]
https://root.cern.ch/

> ROOT is ...
> A modular scientific software framework. It provides all the functionalities needed to deal with big data processing, statistical analysis, visualisation and storage. It is mainly written in C++ but integrated with other languages such as Python and R.

Interesting for our project may be [the ROOT file format](https://root.cern.ch/input-and-output) as a possible alternative to HDF5. See also [this discussion on the ROOT forums](https://root-forum.cern.ch/t/root-file-vs-hdf5/20115/2) for some comparison points.

**Comment by uellue** [comment]
Hm, do we need any of these points?

**Comment by uellue** [comment]
Closing here since LiberTEM took a different path. :-)
