### ISSUE TITLE
github releases: left-over drafts of continuous releases

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#414]
For some reason, there are sometimes draft releases that litter the releases tab (only for members of the LiberTEM repo, but still...). I already deleted some, but here is a recent example: https://github.com/LiberTEM/LiberTEM/releases/tag/untagged-38436bc187afc7aa3aa8

This is somewhat strange, as all releases are created with `draft: False`...

**Comment by uellue** [comment]
Still current

**Comment by sk1p** [comment]
Probably fixed in https://github.com/LiberTEM/LiberTEM/pull/1301
