### ISSUE TITLE
Make sure bad parameters in the file opening parameter cache don't hide good defaults

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#433]
How to reproduce:

Open a dataset with good parameter guessing, for example MIB. Then close and re-open with bad parameters that trigger an error in the opening procedure. Close and re-open again.

Observed behavior:

The bad parameters are cached and there's no obvious or easy way to go back to automatically guessed or default parameters.

Expected behavior:

It is always possible to use the guessed or default parameters again without having to remember them and without having to purge the entire parameter cache.

Possible behaviors to resolve this:

1. Bad parameters that cause an error are not cached. Disadvantage: ALL updated parameters would likely have to be entered again, not just the bad ones.
2. Guessed parameters are always shown in addition to cached values and/or can be used with an easy method, for example clicking on a button next to an input field. This would be the more user-friendly choice.

**Comment by sk1p** [comment]
There is now a per-form reset button, which resets all parameters (except name) to the detected ones. I think a per-field variant is overkill for now, as most formats don't have many parameters. Should revisit this when adding new formats!
