### ISSUE TITLE
Opening the "Glasgow" BLO file with a nonsensical large tileshape trips LiberTEM

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#434]
How to reproduce:

Open the Glasgow BLO file or likely other files that allow setting a tile shape. Use a very large tile shape, such as 1000,800,128,128 that is much larger than the entire dataset, and run an analysis.

Update: This doesn't seem to happen with MIB files!

Observed behavior:

LiberTEM tries to allocate a lot of memory on the workers, despite the entire file being much smaller than the given tile size. This causes the jobs to fail eventually. After some time, the bad jobs "die" and LiberTEM is back to normal.

Expected behavior:

LiberTEM recognizes nonsensical parameters, such as tiles that are larger than the dataset and/or memory limits and triggers an error with an informative message.

**Comment by sk1p** [comment]
This should now be fixed, as `tileshape` can't be specified anymore (#706)
