### ISSUE TITLE
Check and optionally update default tileshape behavior for BLO files

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#435]
How to reproduce:

Open a BLO file that is not in the parameter cache, for example the Glasgow file.

Observed behavior: The default tile shape is 1,8,128,128. However, the signal dimension of this dataset is (144,144), which makes (128,128) seem like an odd choice.

Question: Is this sensible, is the tileshape parameter still necessary at all for BLO, and/or can we guess better defaults? Perhaps something like (1, 6, 144, 144)?

Since BLO files tend to be small, this is not a big issue in practice at the moment.

**Comment by sk1p** [comment]
Hm. This is kind-of related to #247 - ideally the parameter would not exist (maybe we can remove it for 0.3?) I would prefer to have a global (or maybe even per-node) setting "default block size" or similar, which guides the setting of the tileshape. It could default to be initialized from CPU cache size, if we can determine it reliably (Maybe psutil provides something? Could not find anything on a first glance).

**Comment by uellue** [comment]
Refs #706
