### ISSUE TITLE
Close error messages with keyboard

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#437]
How to reproduce:

Trigger an error in the file opening dialogue, for example by opening a non-existent file through the path input field. Naturally, one would confirm the path with "enter".

Observed behavior:

The error message can only be closed with the mouse, while the keyboard still seems to be focused on the input field. Pressing "enter" with the error message in the foreground attempts to open the file again. The error message has to be closed by mouse. Afterwards, the input field doesn't have focus anymore.

Expected behavior:

The error message can be closed by keyboard, intuitively by pressing Enter. Afterwards, the last input field has focus again so that the user can correct the path.

**Comment by sk1p** [comment]
I chose Escape as key - for me, Enter always has the connotation of activating the currently focused element - maybe the error messages could have a more prominent "close" button, which also has keyboard focus...
