### ISSUE TITLE
On Windows 10, execution of the server process stops upon clicking into the cmd window

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#44]
This is the behavior of the windows cmd.exe shell on Windows 10 with QuickEdit Mode activated, the default: 

https://stackoverflow.com/questions/33883530/why-is-my-command-prompt-freezing-on-windows-10

The behavior has confused me several times. The easiest fix is to deactivate QuickEdit Mode. If there's a way around this that doesn't require user action is another question. An installer or self-contained version #39 can probably handle this better. For now, this behavior should at least be documented.

**Comment by sk1p** [comment]
possible fix https://stackoverflow.com/a/13656941/540644 - need to look into doing this via ctypes
