### ISSUE TITLE
Update documentation and examples

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#45]
- [x] update example notebooks
  - [x] replace all "old API" usage with the new, simpler API
  - [x] maybe keep a single "low level API" notebook
  - [x] add an example with a more complex mask
- [x] installation on windows
- [x] usage: user interface
- [x] usage: API introduction
- [x] API documentation for a subset of functionality
- [x] update README to reflect the current project status

**Comment by woozey** [comment]
Great! Thanks! I still can't really test it, having every time new issues with the data conversion...

**Comment by uellue** [comment]
Checked "usage: user interface" via 2e277bf

**Comment by sk1p** [comment]
I added autogenerated API documentation for the Python API to the docs. For now I'm referencing the example notebooks as an introduction. 

Now, there are two notebooks left using LiberTEM internals:

 - multicore_scalability: That can't really be built without accessing the internals (yet), so I'll keep it this way for now
 - hyperspy_example: the center of mass notebook is a better example for hyperspy interaction IMHO (contains messy progress bar stuff, too), this one is more suited as HDFS/cluster example. Get rid of it, or fix the API to accept a connection URI to connect to an existing cluster, and salvage it that way?

I think the peak selector example can be seen as a more complex mask example, so I checked that.

**Comment by uellue** [comment]
Honestly, my heart is not attached to it. So the "correct" way for Hyperspace is to kick off the calculation and construct a signal with the result afterwards, like the center of mass example does it now? :-) I'm fine with either way, just want to clarify.

**Comment by uellue** [comment]
@sk1p In the API reference I could only see the internal API, not the Python API. At least I couldn't find the definition of `Context.run()`, or am I blind?

**Comment by uellue** [comment]
@sk1p found the reference, I moved it where I expected to find it. :-)

**Comment by sk1p** [comment]
Yeah, sorry about that, the API docs are very much WIP. I only added the documentation for the internal API because I had some references from the Python API to DataSet, Job etc...

**Comment by uellue** [comment]
Checked README via 605e3b5

**Comment by uellue** [comment]
Closed since we have the examples covered as well. The "multicore scalability" can work as low-level API example.
