### ISSUE TITLE
Python 3.8 support, .travis.yml

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#452]
There is a travis config linter available here: https://config.travis-ci.com/explore - it shows that we are still using some old keywords, are missing others etc. - needs to be updated accordingly!

**Comment by sk1p** [comment]
Moving this to 0.5 as dask.distributed 2.11 won't be released soon enough

**Comment by sk1p** [comment]
> Moving this to 0.5 as dask.distributed 2.11 won't be released soon enough

PR in distributed is now merged, can go forward with this once the release is out

**Comment by uellue** [comment]
@sk1p referring to https://github.com/LiberTEM/LiberTEM/pull/482#issuecomment-610323771: Include in 0.5 or bump to 0.6?

**Comment by sk1p** [comment]
Third option: close in favor of #565 ?

**Comment by uellue** [comment]
> Third option: close in favor of #565 ?

Ok, that's easy! 😄
