### ISSUE TITLE
Export calculation result

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#46]
Currently, the GUI shows a false color map of the calculation result.

It should be possible to export the result as numerical values, for example as raw binary, HDF5 or CSV so that it can be used for further processing.

**Comment by sk1p** [comment]
Digital micrograph supports a weird CSV format, which is just rows of intensity values separated by commas - we should also export to this dialect, in addition to the more straight forward "x, y, intensity1, ..., Intensity_n"

Maybe also float .tiff images?

**Comment by bdalevin** [comment]
I would like to add a comment to this issue. 
Allowing users to save a float .tif image from the GUI would be extremely helpful for many of my users. 
Please implement this as soon as you can.

**Comment by sk1p** [comment]
Thank you for the feedback! We will prioritize this issue and plan to implement this for the 0.5 release.

**Comment by sk1p** [comment]
The basic functionality is now implemented, with support for HDF5, NPZ, TIFF, and RAW formats. It can be tested by [installing LiberTEM from git](https://libertem.github.io/LiberTEM/install.html).

If you have any feedback, let us know in this issue, the [followup issue](https://github.com/LiberTEM/LiberTEM/issues/687) or via E-Mail. Thanks!
