### ISSUE TITLE
Error message from not finding a file persist and confuses the user

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#50]
When trying to open a non-existing file, a detailed error message is displayed. Usually a user will correct the path and try to open the file again.

Observed behavior:
The previous error message persists alongside the now opened dataset, which creates the impression that an error occurred with the newly opened file.

Expected behavior:
The previous error message is cleared when a new file is opened. Only error messages pertaining to the last command are displayed in the UI.

**Comment by sk1p** [comment]
Maybe it would make sense to make errors modal, see e.g. [the semantic ui docs](https://react.semantic-ui.com/modules/modal/) for an example. That way the user has to dismiss the error(s) that occurred, so they are neither missed nor do they linger after losing relevance.
