### ISSUE TITLE
Implement and use type system

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#506]
Currently, we use type hinting only sparsely in the API.

In the future, we should pervasively specify types in such a way that they are both machine and human readable.

This helps to make our documentation clear and precise. Additionally, it may help to find issues by using automated checking routines like [mypy](http://mypy-lang.org/). The LiberTEM code base has grown to such a volume that such tests help to maintain coherence across the project.

Parts of this issue that can be solved individually:

- [x] Integrate a type checker like mypy into our CI pipeline
- [ ] Types for the `Context` class
  - [ ] Parameters
  - [X] Return types, done in #643 
- [ ] Types for all parts of the UDF interface

**Comment by sk1p** [comment]
See also: https://glyph.twistedmatrix.com/2020/07/new-duck.html

**Comment by sk1p** [comment]
As an update, much of `Context` now does have type hints available - while the UDF interface itself is still a bit patchy. There is now opt-in mypy checking in pre-commit, via the [.mypy-checked file](https://github.com/LiberTEM/LiberTEM/blob/master/.mypy-checked).

**Comment by uellue** [comment]
We are using type hints in pretty much all new code. Closing here!
