### ISSUE TITLE
Feature request: standard deviation with respect to reference pattern

### ISSUE THREAD

**Issue by woozey** [LiberTEM/LiberTEM#57]
Having reference diffraction pattern intensity`R(kx, ky)` (`kx` and `ky` are coordinates or indexes in diffraction plane), the standard deviation for each diffraction pattern `Dxy(kx, ky)` at each scan point `(x, y)` can be written as:
![](https://latex.codecogs.com/gif.latex?STD_%7Bx%2Cy%7D%20%3D%20%5Csqrt%20%5Cfrac%7B%5Csum_%7Bkx%2C%20ky%7D%20%28D_%7Bx%2Cy%7D%28kx%2Cky%29%20-%20R%28kx%2Cky%29%29%5E2%7D%7BN%7D)
where `N` is the total number of pixels in diffraction images.

**Comment by uellue** [comment]
Implemented for most practical purposes with `StdDevUDF`, incl. GUI support. Deviation from a given reference could be easily implemented with a UDF by now.
