### ISSUE TITLE
Document available test datasets

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#588]
Thx @twentyse7en  for the suggestion!

Thx @cophus again for the bullseye data. :-)

- [x] Examples for a collection of public datasets in LiberTEM-Examples
- [x] Link to files, document where and how to get data in documentation
- [x] Base feature documentation on public datasets, such as screenshots

**Comment by twentyse7en** [comment]
Sorry I forget to add source of dataset used for updating screenshot as you mentioned.
where exactly should I mention the dataset?

**Comment by sk1p** [comment]
> Sorry I forget to add source of dataset used for updating screenshot as you mentioned.
> where exactly should I mention the dataset?

I would suggest adding a proper citation directly in the GUI usage docs at minimum. In addition, we can have a section "public datasets" or similar that has a collection of interesting data.

**Comment by twentyse7en** [comment]
That would be great :+1:

**Comment by twentyse7en** [comment]
Where are you planning to add new section ?

**Comment by sk1p** [comment]
> Where are you planning to add new section ?

Hm, this is not so easy to decide. But as we are planning to do a documentation review soon™ anyways, it could start out as a new top-level item in the TOC (top level means it will be listed as one of the items in the Contents list on the left side). Later, as part of the review, we will re-structure our documentation anyways.

It should be linked from all relevant sections, for example "Loading data" for people curious how things work but not having any data of their own, or before loading data in the "GUI usage" section to allow people to follow along on their own machines.
