### ISSUE TITLE
Automate testing of example notebooks

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#595]
The manual QA of checking the example notebooks could be augmented by [pytest-notebook](https://pypi.org/project/pytest-notebook/), which does snapshot testing for notebooks. I think it would be mostly useful for smoke testing, i.e. making sure the examples at least keep running after changes in LiberTEM.

Needs access to the datasets used in the examples.

**Comment by uellue** [comment]
This mostly working now: https://libertem.github.io/LiberTEM/contributing.html#example-notebooks

Closing! :-)
