### ISSUE TITLE
Suboptimal performance with small data sets and many workers

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#60]
A 4 GB file is processed on a remote high-performance machine with 18 CPU cores and 256 GB RAM. The GUI is forwarded with SSH. 

Observed behavior:
The processing takes about 3 s, while a local machine with 4 cores performs the same analysis in less than 1 s. The GUI shows how the image builds up in many narrow stripes.

Expected behavior: 
The processing is at least as fast as on a 4-core local machine.

Ideas what causes this:
The libertem-server process has a high CPU load, while the workers have a very low load. It seems that processing the incoming results takes more processing power than calculating the result. Since a whole result frame is calculated for each incoming slice, the server process has a lot of work to do.

Suggestion: 
Debouncing of result frame recalculation.

**Comment by sk1p** [comment]
I committed a partial fix that debounces the result visualization to max once per 300ms, this should already help. There is still at least one potential bottleneck: the result copying is for now done in the main thread, for simplicity reasons. This blocks the event loop for a little bit, but should not be as grave as the visualization thing.

**Comment by uellue** [comment]
Processing the same data set under the same conditions takes less than a second now. Thx @sk1p !
