### ISSUE TITLE
Performance regression for disk analysis with remote Dask cluster

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#602]
Using a remote Dask cluster running a disk analysis leads to a massive performance regression in comparison to a plain mask analysis.

Setup: Dedicated dask cluster running on moellenstedt. connection to the cluster through VPN and SSH tunneling from a Windows machine over the internet, and locally from moellenstedt itself over TCP to localhost for comparison purposes.

Versions: LiberTEM (nearly) master, dask and distributed 2.10.1 /2.10.0 (latest)

![image](https://user-images.githubusercontent.com/25689052/74548347-f170d080-4f4d-11ea-96ce-21a9ce1c9248.png)

The same effect is observable in the GUI, both with `libertem-server` running on moellenstedt and on a remote Windows machine. 

Connecting to the same cluster from a Jupyter notebook on moellenstedt in the same Python environment triggers the error as well, meaning this is not a cross-platform or version mismatch issue.

An excessive size of the pickled tasks can be excluded judging from the output of debugging code. The regression occurs on repeated execution. The CPU is busy during that time, judging from the output of `top`.

It does not occur when running the same test on the same machine with a local cluster directly with JupyterHub. The performance with a local cluster is 4x (mask analysis) to 50x (disk analysis) better compared to the remote cluster over TCP to localhost.

![image](https://user-images.githubusercontent.com/25689052/74548547-562c2b00-4f4e-11ea-9cd7-c3d1fb1b1c2d.png)

It also doesn't occur when starting libertem-server with a local cluster on moellenstedt.

**Comment by uellue** [comment]
- [ ] Test with stand-alone Dask, minimal reproducer
- [ ] Bisect

**Comment by uellue** [comment]
The regression was caused by not setting the thread count for the stand-alone workers correctly. Refs #546

**Comment by sk1p** [comment]
Ugh, okay. Well done tracking this down, thanks!

**Comment by uellue** [comment]
@sk1p Well, I dug out a new problem in the process: #684 🙄
