### ISSUE TITLE
Allow final postprocessing on the central node in an UDF

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#628]
Discussion with @sk1p and @Brow71189:

Currently, final postprocessing of an UDF's results is performed in a `run_*()` function that is not part of the UDF. If live updating results are required, this has to be re-implemented by the routine that is consuming the live-updating raw results.

In the future, an UDF should be able to specify a final processing routine that transforms raw results into something useful for the user. `StdDevUDF` would be a prime non-trivial example where this is required.

It should be possible to perform the transformation for each merging step so that incremental postprocessed results are available.

**Comment by sk1p** [comment]
Just for naming: how about `UDF.finalize()`?

One important point: making this a method on the UDF will currently limit us to finalizing only using the result of one UDF. This is not necessarily bad, just something to keep in mind.

**Comment by uellue** [comment]
`finalize()` is the name of a destructor in many languages: https://en.wikipedia.org/wiki/Finalizer.

What about `consolidate()`?

**Comment by uellue** [comment]
It should probably be a pure function that doesn't modify the state of the UDF. In that case we can call it whenever we need consolidated partial results.

**Comment by sk1p** [comment]
> It should probably be a pure function that doesn't modify the state of the UDF. In that case we can call it whenever we need consolidated partial results.

:+1:

> finalize() is the name of a destructor in some languages

Tried my best to forget about Java :grin:

> What about consolidate()?

Hmm, to me this sounds like a merge/reduce-ish operation, but really this could be any kind of transformation. What about the more general `get_results`? It may also make it clear that it is a getter and not really a function where you should put anything computationally intensive

**Comment by uellue** [comment]
> What about the more general `get_results`?

:+1:
