### ISSUE TITLE
Releasing docs: add item about handling deprecations

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#629]
Before cutting a release, search the code base for `DeprecationWarning`s that are supposed to be removed in that release. Possibly also add a "things that will be removed in the next release" section in the changelog for proper messaging.

**Comment by twentyse7en** [comment]
I would like to contribute.

**Comment by sk1p** [comment]
> I would like to contribute.

Okay! Did you already find the release checklist? This issue is about adding new items in there to remind us to take care of deprecations.

**Comment by sk1p** [comment]
Another point for the release checklist: Add the current LiberTEM version to CVL @ https://github.com/Characterisation-Virtual-Laboratory/CharacterisationVL-Software

**Comment by twentyse7en** [comment]
Where can I find release checklist ?

**Comment by sk1p** [comment]
It [on the releasing page](https://libertem.github.io/LiberTEM/releasing.html#release-checklist), which is linked from [Contributing -> Advanced](https://libertem.github.io/LiberTEM/contributing.html#advanced)

**Comment by twentyse7en** [comment]
So I need to add items in checklist which will removed in release 0.5, right ?

**Comment by sk1p** [comment]
The idea is to add general checklist items for handling deprecation and publishing to CVL, not specifically for one version

**Comment by twentyse7en** [comment]
For finding `DeprecationWarning` I have gone through `LiberTEM/src`. Do I have to search in entire code(`LiberTEM/`) or just `Libertem/src`

**Comment by sk1p** [comment]
Hmm, you are overthinking it. The idea is just to have a *very* simple item in the release checklist to remind us to take care of deprecations. There doesn't need to be a list of concrete warnings at all, and also no need for a detailed description: it is supposed to be terse. The target audience of the release checklist are experienced contributors of LiberTEM who want to either a) do a release themselves or b) help out with doing the quality assurance.

**Comment by twentyse7en** [comment]
Thx, I was going in a different direction :sweat_smile: Hope the changes made in PR are something you expects.
