### ISSUE TITLE
UDF: attribute access in merge

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#631]
Instead of requiring `dict`-like access, also allow access by attribute name, i.e. `dest.pixelsum_nav_raw[:] += src.pixelsum_nav_raw`

Otherwise there is a strange disconnect between the `process_*` functions and `merge`.

**Comment by sayandip18** [comment]
Seems like `sum.py`, `logsum.py`, `raw.py` and `masks.py` are the only files that have this kind of access.  
The rest should be modified in a way to allow this, right?

**Comment by sayandip18** [comment]
What exactly are the purpose of these quotation marks inside the function [here](https://github.com/LiberTEM/LiberTEM/blob/bd29333c745b39186d0bc04bc0c9e0d701752fa8/src/libertem/udf/sum.py#L31)?

**Comment by sk1p** [comment]
> What exactly are the purpose of these quotation marks inside the function [here](https://github.com/LiberTEM/LiberTEM/blob/bd29333c745b39186d0bc04bc0c9e0d701752fa8/src/libertem/udf/sum.py#L31)?

They are the docstring of the method, so in this case, they override the docstring of the base class to be an empty string. We do this sometimes if it doesn't make sense to have the docstring of the base class visible in the documentation of the subclass.

**Comment by sk1p** [comment]
> Seems like `sum.py`, `logsum.py`, `raw.py` and `masks.py` are the only files that have this kind of access.
> The rest should be modified in a way to allow this, right?

I'm not sure I follow - none of the `merge` functions can use the attribute-way of accessing the buffers right now, they all require `dict`-like access.

**Comment by sayandip18** [comment]
> 
> I'm not sure I follow - none of the `merge` functions can use the attribute-way of accessing the buffers right now, they all require `dict`-like access.

My bad. I am still a bit confused though. The `process_*` methods in the utility UDF classes have `self.results.buffername` (like [here](https://github.com/LiberTEM/LiberTEM/blob/d19b4e5d6cf1ebae929575381debc4b59bdf342c/src/libertem/udf/sumsigudf.py#L28)). I get it that it is accessing the dictionary returned by `get_result_buffers()`, but there is no attribute called `results` in UDF class!
