### ISSUE TITLE
Annular CoM detection in GUI

### ISSUE THREAD

**Issue by matkraj** [LiberTEM/LiberTEM#633]
Hello @uellue and @sk1p,
It would be beneficial for some applications (Lorentz STEM) to include annular mask for centre of mass imaging. This would allow filtering of large proportion of diffraction contrast from magnetic and electric field imaging in nano-diffraction. It would be a great feature for live imaging applications. The technique was first introduced with annular DPC detectors in https://doi.org/10.1109/20.104427.

**Comment by uellue** [comment]
@matkraj That's a nice point! With the current version one can do this with scripting. Implementing this in the GUI is not too difficult, too. I'm including this in our GSoC ideas list, together with the other remaining items of #31 .

Is this more of a general idea or would this be used asap by someone?

How does this compare with correlation-based detection of the shift?

**Comment by matkraj** [comment]
@uellue It is a more general idea. It will be a very useful feature when live imaging. 

Gradient cross-correlation will be always better. Interestingly, the two techniques can be somehow similar if one could make an annular detector with variable position and beam only overlapping a tiny proportion over the inner quadrants.

**Comment by uellue** [comment]
> It will be a very useful feature when live imaging.

Actually, the correlation will also work with live data in LiberTEM. Just missing a GUI at the moment. 😄
