### ISSUE TITLE
Progress bar support for `Context.map` and `Context.run`

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#644]
Support in `Context.map` is straight-forward, same for `Context.run` with UDF-based analyses; I think adding progress bar support for the deprecated job-based analyses is not important, even if it is possible.

**Comment by twentyse7en** [comment]
Can you provide some more details. Do we use any library for progress bar?

**Comment by sk1p** [comment]
Yes, we are using `tqdm`. But in this case, you don't even need to know this, as `Context.run_udf` already has a `progress` parameter, and both `map` and `run` call `run_udf` under the hood.
