### ISSUE TITLE
If file format can't be determined automatically, explicitly ask the user

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#65]
Currently the user needs to set a few parameters, depending on the file format. We can do better and do auto detection. The workflow then looks like this:

 * User selects a file in the file browser
 * LiberTEM server tries to detect the format and parameters
 * LiberTEM client shows open form pre-filled with detected parameters
 * User can still change parameters and even select different format
 * User confirms selection and LiberTEM opens the dataset

**Comment by sk1p** [comment]
This should be considered high-priority, as it is a real stumbling block, especially for new users.

If the file format can't be determined automatically, we should explicitly ask the user in the next step!

**Comment by uellue** [comment]
Full ack! :+:

**Comment by sk1p** [comment]
> If the file format can't be determined automatically, we should explicitly ask the user in the next step!

Everything except this part is now implemented.

**Comment by uellue** [comment]
Autodetection seems to work well for all formats we support by now. Closing here!
