### ISSUE TITLE
RAW: Dataset with Direct I/O enabled fails to load on Windows

### ISSUE THREAD

**Issue by AnandBaburajan** [LiberTEM/LiberTEM#658]
On Windows (with Python 3.7), trying to load a raw dataset with direct I/O enabled results in the following error: `module 'os' has no attribute 'O_DIRECT'`

I assume this only occurs on Windows as in #599 it is stated that "When running an analysis, note that direct I/O is enabled".

**Comment by sk1p** [comment]
Thanks for opening the issue! 
 
> I assume this only occurs on Windows as in #599 it is stated that "When running an analysis, note that direct I/O is enabled".

Indeed, Windows doesn't support direct I/O using the same API as Linux - instead, the `FILE_FLAG_NO_BUFFERING` flag, and the platform-specific `CreateFile` and `ReadFile` functions are used. If you are curious how this would work, see [the documentation on CreateFileA by Microsoft](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea), [a general article about file buffering](https://docs.microsoft.com/en-us/windows/win32/fileio/file-buffering?redirectedfrom=MSDN) and [this stackoverflow question](https://stackoverflow.com/questions/40249807/how-to-sector-align-data-in-a-buffer-win32file-file-flag-no-buffering).

Supporting Direct I/O on Windows has not been a priority for us, as most heavy-duty users (data much larger than available RAM, possibly very fast storage) are using Linux-based servers/workstations for data processing.

I think the questions now becomes: how should be handle this error?

For the Python API, I would strongly suggest we keep raising an `Exception`, to prevent surprises (although the message should be more clear than this one). Or maybe we should raise a `RuntimeWarning` or `UserWarning`? A warning may not reach the user in case of embedding LiberTEM in another application, though.

For the GUI, the ideal way would be IMHO to open the file without direct I/O and log a warning - but we don't have a warning log in the GUI yet. Alternatively, "grey out" the checkbox if the parameter is not supported on the platform. A general implementation of that would require passing more data from the "detect" method of the dataset to the GUI, or dynamically generating the open forms from some dynamic description (related to #316). Maybe the best immediate solution would be to just display a more user-friendly error message.
