### ISSUE TITLE
Numba testing pitfalls?

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#663]
As mentioned in the numba gitter, there are some more differences when numba is disabled:

https://github.com/pygae/clifford/blob/63f82795cc5e90385afc734bd4341f964593dd71/clifford/_numba_utils.py

**Comment by uellue** [comment]
Does it mean we should do sth about it or is it just for information?

**Comment by sk1p** [comment]
That's the question - do we need to do something? For now, it's just here as a reminder

**Comment by uellue** [comment]
It doesn't seem to affect us much. We use cloudpickle anyway. Closing!
