### ISSUE TITLE
Poster for Helmholtz Imaging Platform matchmaking workshop

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#671]
**Processing of large-scale binary data**

--> Poster: [LiberTEM poster for HIP-0.3-web.pdf](https://github.com/LiberTEM/LiberTEM/files/4312021/LiberTEM.poster.for.HIP-0.3-web.pdf) <--

# Interest in projects

* New applications for LiberTEM
  * Automation
  * Information extraction
  * Live data processing
  * Back-end for other software
* Distributed high-performance data processing
* Advanced imaging
* Data management, data logistics
* Open Data, FAIR

# See related

* Poster P08: Ptychography 4.0, https://github.com/Ptychography-4-0/ptychography/issues/24
* Poster P26: Imaging at Institute of Radiation Physics @HZDR: https://owncloud.hzdr.de/index.php/s/19nvqlWrUkan4zb (password: imagingFWK)
* Poster P27: Alpaka, https://owncloud.hzdr.de/index.php/s/69Zip2M4zJYhoX3 (poster, password: alpakaPoster) and https://github.com/ComputationalRadiationPhysics/alpaka

# Contact

We are looking forward to collaborate on new project ideas! Contact us to arrange a follow-up discussion for details.

Presenting author: Alexander Clausen <a.clausen@fz-juelich.de>
Gitter chat: https://gitter.im/LiberTEM/Lobby

# LiberTEM creators

@sk1p @uellue @kruzaeva @woozey @AnandBaburajan @twentyse7en @jan-car @irahulcse @Iamshankhadeep @magnunor @cophus @probonopd @ozej8y @jaewshin Knut Müller-Caspary @rafaldb

**Comment by sk1p** [comment]
Note that this has just been converted into a remote video conference, so it turns out the posters won't actually be physically printed.

**Comment by uellue** [comment]
> Note that this has just been converted into a remote video conference, so it turns out the posters won't actually be physically printed.

For that reason converting this issue to a landing page! :-)

**Comment by uellue** [comment]
Closing since inactive :-)
