### ISSUE TITLE
Include LiberTEM in "TEM" community on Zenodo.org

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#676]
Via @sk1p:

https://www.zenodo.org/communities/tem/search?page=1&size=20

We could try to include this community in the Zenodo template for LiberTEM.

**Comment by sayandip18** [comment]
Does LiberTEM have any identifier other than DOI?

**Comment by uellue** [comment]
@sayandip18 In what sense an identifier? For what purpose?

**Comment by sayandip18** [comment]
> 
> 
> @sayandip18 In what sense an identifier? For what purpose?

Actually I was checking out how LiberTEM could have been uploaded to Zenodo and saw that there was a section titled "Related/Alternate identifiers". 

"Specify identifiers of related publications and datasets. Supported identifiers include: DOI, Handle, ARK, PURL, ISSN, ISBN, PubMed ID, PubMed Central ID, ADS Bibliographic Code, arXiv, Life Science Identifiers (LSID), EAN-13, ISTC, URNs and URLs" - this was the in the description below.
