### ISSUE TITLE
Button to make the server stop

### ISSUE THREAD

**Issue by twentyse7en** [LiberTEM/LiberTEM#698]
An example as in Jupyter notebook :

![quit](https://user-images.githubusercontent.com/59721339/78147599-5d04f380-7451-11ea-9f50-a541dfa879c9.png)

**Comment by uellue** [comment]
Is this more of a "nice to have" or does it solve a specific issue?

**Comment by twentyse7en** [comment]
"nice to have"

**Comment by sk1p** [comment]
> does it solve a specific issue?

Possibly the issue of stopping the LiberTEM server if you didn't start it from a terminal, for example via https://github.com/sk1p/libertem-jupyter-proxy

**Comment by uellue** [comment]
> > does it solve a specific issue?
> 
> Possibly the issue of stopping the LiberTEM server if you didn't start it from a terminal, for example via https://github.com/sk1p/libertem-jupyter-proxy

Ok, good point!

**Comment by twentyse7en** [comment]
> 
> Possibly the issue of stopping the LiberTEM server if you didn't start it from a terminal, for example via https://github.com/sk1p/libertem-jupyter-proxy

I would like to work on this, can you give some details regarding jupyter part.

**Comment by sk1p** [comment]
You can try this yourself: run LiberTEM from jupyterlab, and kill the libertem-server process. What happens: does libertem-server stay dead, or is it revived? If it is revived, why is that? Example: the GUI keeps doing HTTP/websocket requests → this is easily fixable, other example: jupyter-proxy-server or how it's called just restarts any child processes → not so easy to fix, as it means we need to tell it to stop somehow

**Comment by sk1p** [comment]
> kill libertem-server process alone

Using the process manager of the operating system, or, for example, `kill` on Linux.

**Comment by twentyse7en** [comment]
Hey @AnandBaburajan can we collaborate on this issue?

**Comment by AnandBaburajan** [comment]
> Hey @AnandBaburajan can we collaborate on this issue?

Sure! I'll check the details and get back to you.

**Comment by AnandBaburajan** [comment]
@twentyse7en So which part do you want me to focus on? Stopping the server or the button GUI part?

**Comment by twentyse7en** [comment]
No problem, I will give a try.
