### ISSUE TITLE
Release 0.5.0

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#701]
# Release checklist

## Before (using a release candidate package)

- [x] Review open issues and pull requests
- [x] Handle deprecation, search the code base for :code:`DeprecationWarning`
  that are supposed to be removed in that release.
- [ ] Full documentation review and update,
  - [x] including link check using ``sphinx-build -b linkcheck "docs/source" "docs/build/html"``
- [x] Update the expected version in notes on changes, i.e. from :code:`0.3.0.dev0`
  to :code:`0.3.0` when releasing version 0.3.0. #724 
- [x] Update and review change log in :code:`docs/source/changelog.rst`, merging
  snippets in :code:`docs/source/changelog/- [ ]/` as appropriate. #724 
- [x] Update the JSON files in the ``packaging/`` folder with author and project information #736 
- [x] Edit `tox.ini` to exclude flaky tests temporarily from release builds
- [x] Create a release candidate using :code:`scripts/release`. See :code:`scripts/release --help` for details.
- [x] `Confirm that wheel, tar.gz, and AppImage are built for the release candidate on
  GitHub <https://github.com/LiberTEM/LiberTEM/releases>`_
- [x] Confirm that a new version with the most recent release candidate is created in the
  `Zenodo.org sandbox <https://sandbox.zenodo.org/record/367108>`_ that is ready for submission.
- [x] Install release candidate packages in a clean environment
  (for example:
  :code:`pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple 'libertem==0.2.0rc11'`)
- [x] For the GUI-related items, open in an incognito window to start from a clean slate
- [x] Correct version info displayed in info dialogue?
- [x] Link check in version info dialogue
- [x] Make sure you have test files of all supported types available
    - [ ] Include floats, ints, big endian, little endian, complex raw data
- [x] Open each test file
    - [x] Are parameters recognized correctly, as far as implemented?
    - [x] Any bad default values?
    - [x] Does the file open correctly?
    - [x] Have a look at the dataset info dialogue. Reasonable values?
- [x] Perform all analyses on each test file.
    - [x] Does the result change when the input parameters are changed?
    - [x] All display channels present and looking reasonable?
    - [x] Reasonable performance?
    - [x] Use pick mode.
- [x] Re-open all the files
    - [x] Are the files listed in "recent files"?
    - [x] Are the parameters filled from the cache correctly?
- [x] Try opening all file types with wrong parameters
    - [x] Proper understandable error messages?
- [x] Pick one file and confirm keyboard and mouse interaction for all analyses
    - [ ] Correct bounds check for keyboard and mouse?
- [x] Check what happens when trying to open non-existent files or directories in the GUI.
    - [x] Proper understandable error message?
    - [x] Possible to continue working?
- [x] Shut down libertem-server while analysis is running
    - [x] Shut down within a few seconds?
    - [x] All workers reaped?
- [ ] Check what happens when trying to open non-existent files by scripting.
    - [ ] Proper understandable error message? TODO automate?
- [ ] Check what happens when opening all file types with bad parameters by scripting
    - [ ] Proper understandable error message? TODO automate?
- [x] Run all examples
- [x] Run libertem-server on Windows, connect to a remote dask cluster running on Linux,
  open all file types and perform an analysis for each file type.
- [x] Use the GUI while a long-running analysis is running
    - [x] Still usable, decent response times?
- [x] Confirm that pull requests and issues are handled as intended, i.e. milestoned and merged
  in appropriate branch.
- [x] Add the current LiberTEM version to
  `CVL <https://github.com/Characterisation-Virtual-Laboratory/CharacterisationVL-Software>`_ (add both the singularity and the .desktop file!)

## After releasing on GitHub

- [x] Confirm that all release packages are built and release notes are up-to-date
- [x] Install release package
- [x] Confirm correct version info
- [x] confirm package upload to PyPi
- [x] Publish new version on zenodo.org
- [x] Update documentation with new links, if necessary
    - [x] Add zenodo badge for the new release to Changelog page
- [x] Send announcement message on mailing list
- [x] Bump version in master branch to next .dev0

**Comment by sk1p** [comment]
I'm closing this now, only pending issue IIRC was documentation review, which we will have to re-start before the 0.6 release anyways.
