### ISSUE TITLE
Spurious test failures

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#713]
Mostly seen on Win/Mac OS X until now, examples:

- https://travis-ci.org/github/LiberTEM/LiberTEM/jobs/674037981
- https://ci.appveyor.com/project/sk1p/libertem/builds/32124574/job/sguyy9uai3qb7l3q

**Comment by sk1p** [comment]
Some more:
https://travis-ci.org/github/LiberTEM/LiberTEM/jobs/674610052
https://travis-ci.org/github/LiberTEM/LiberTEM/jobs/674610053
https://travis-ci.org/github/LiberTEM/LiberTEM/jobs/674610054
https://travis-ci.org/github/LiberTEM/LiberTEM/jobs/674610055

**Comment by uellue** [comment]
This should be addressed with #921, right? Closing now, we can re-open or open a new issue in case this comes up again.
