### ISSUE TITLE
Add an experimental HTTP-based I/O backend

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#717]
For example, could start with an S3 backend.

- [ ] perform all ad-hoc reads (for example for file headers) via the I/O backend
- [ ] support for directory browsing in the I/O backend

**Comment by uellue** [comment]
Not sure if we want to keep this open to document that it would be possible?

**Comment by sk1p** [comment]
I'll close this for now, this was more of an idea for exploration and not a priority for users.
