### ISSUE TITLE
Refactor: info part of dataset detect results should not be part of the dataset params type

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#726]
See discussion in the commits of #700 - instead of keeping [a "blacklist" of info parameters](https://github.com/LiberTEM/LiberTEM/blob/5cfd119e6eea084011f08278d71aa90f05666939/client/src/dataset/components/DatasetParams.tsx#L21), the ["info" part (dataset_paths here)](https://github.com/LiberTEM/LiberTEM/blob/5cfd119e6eea084011f08278d71aa90f05666939/client/src/messages.ts#L105) should be properly separated from the rest of [the `DatasetFormParams` type](https://github.com/LiberTEM/LiberTEM/blob/5cfd119e6eea084011f08278d71aa90f05666939/client/src/messages.ts#L152)

**Comment by AnandBaburajan** [comment]
Note to self: Fix https://github.com/LiberTEM/LiberTEM/pull/732 too

**Comment by sk1p** [comment]
See also: #793
