### ISSUE TITLE
Glitch in file opening dialogue

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#741]
How to reproduce in the GUI, in this case mixing EMPAD XML and BLO:

* Click "+Browse"
* Select a file to get the file loading dialogue
* Click "+Browse" again while the previous dialogue is still open
* Select another file
* Click "Load Dataset"

Observed behavior:
* Only one file loading dialogue is visible even if a second file was selected
* The parameters from both file types seem to get mixed up when the dialogue is submitted.

Expected behavior: Two loading dialogues in parallel that work independently and don't mix, or no further browsing possible before loading is concluded.

**Comment by AnandBaburajan** [comment]
@uellue Can I look into and try to solve this?

**Comment by sk1p** [comment]
> Can I look into and try to solve this?

Sure, go ahead!
