### ISSUE TITLE
Add logging level argument to cli

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#743]
To allow users to quickly debug something, the logging level should be configurable from the cli.

**Comment by Iamshankhadeep** [comment]
is it done?

**Comment by sk1p** [comment]
> is it done?

No, the commits referencing this issue statically set the logging level to `INFO`. This issue is about allowing the user to specify the logging level from the CLI.

**Comment by sayandip18** [comment]
> 
> This issue is about allowing the user to specify the logging level from the CLI.

By "level" do you mean `DEBUG`, `INFO`, `WARNING`, etc?

**Comment by sk1p** [comment]
> By "level" do you mean `DEBUG`, `INFO`, `WARNING`, etc?

Exactly.

**Comment by sayandip18** [comment]
How can the user specify these? Aren't they supposed to be in the code?

**Comment by sk1p** [comment]
Log levels appear in different places. One is in code - some function decides to call `someLogger.debug(...)`, and a message with level DEBUG is logged. Then, each logger can be configured to only log specific levels, for example, the code could contain `someLogger.debug(..)` statements, but the logger will only pass them on to the handler if the logger level is set appropriately. Then, handlers can specify the threshold they want to log - if a handler is set to INFO and gets a log message with level DEBUG, it will not handle that message. See also [the official documentation](https://docs.python.org/3/library/logging.html) for details.

The idea of this issue is to allow the user to configure *the logging handler*. By default, only log messages with level INFO should be logged, but if the user hits a problem, they should be able to switch over to DEBUG logging and also get log messages with level DEBUG. Or they could configure the handler level to WARNING or ERROR, and only get more important messages.
