### ISSUE TITLE
Add test cases for contiguous copies in `BufferWrapper`

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#756]
Extracted from #706: Add test cases for flattening the signal dimension of tiles using `libertem.common.buffers.reshaped_view()` #739

**Comment by sayandip18** [comment]
What about [this](https://github.com/LiberTEM/LiberTEM/blob/b8f3c6102142d9fceac1efa790d9d6686f55bce9/tests/common/test_bufferwrapper.py#L57)?

**Comment by sk1p** [comment]
> What about [this](https://github.com/LiberTEM/LiberTEM/blob/b8f3c6102142d9fceac1efa790d9d6686f55bce9/tests/common/test_bufferwrapper.py#L57)?

I think this issue was about a more specific test case, @uellue should know details.

**Comment by uellue** [comment]
@sayandip18 @sk1p This is a test for the function itself, to make sure that it throws an error if the received data can't be flattened without a copy. Test cases for the rest of the system are still missing:

* Make sure only contiguous views are delivered, even if the signal dimension is sliced unfavourably
* Make sure the system throws an error if the slices in the cache overlap
* Make sure the system throws an error if the underlying data is accessed the wrong way while a cached copy exists
* Make sure the contiguous copies are merged back correctly

This is only possible with the new infrastructure for tiled `MemoryDataSet` of #706, while the fix with contiguous copies had to go into 0.5.0 to make `StdDevUDF` work correctly.

**Comment by uellue** [comment]
Refs #814, discussion with @sk1p: Remove test of disjointness from production code and integrate it with the contiguous tests -- call run_for_partition() and check afterwards that the cache keys are disjoint.
