### ISSUE TITLE
Failure to restart libertem-server after closing it on Bash

### ISSUE THREAD

**Issue by sayandip18** [LiberTEM/LiberTEM#759]
To reproduce, do the following

1.  At first, run the server from Git Bash.

2.  After the web-page appears, use the "X" GUI element on the top-right to close the page. Close the console too.

3. Now try to restart the server from either Bash or Anaconda prompt. You will get this
`OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted`

**Comment by sayandip18** [comment]
Can be fixed after #731 is merged

**Comment by uellue** [comment]
I couldn't reproduce this on my system. Both Ctrl-C and shutdown work when LiberTEM is run from Git Bash.
