### ISSUE TITLE
Corrections test still flaky

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#761]
Examples: 

https://travis-ci.org/github/LiberTEM/LiberTEM/jobs/680233941
https://travis-ci.org/github/LiberTEM/LiberTEM/jobs/680432615
https://travis-ci.org/github/LiberTEM/LiberTEM/jobs/680286700

Hope it's okay if I assign this to you, @uellue :grin:

**Comment by uellue** [comment]
> Hope it's okay if I assign this to you, @uellue 😁

Hard to dodge since it is my code that acts up... :-D
