### ISSUE TITLE
Dataset dimension squeezed out

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#791]
How to reproduce:

Process data with nav shape (1,), possibly with aux data

Observed behavior:
```
c:\users\weber\documents\libertem\libertem\src\libertem\common\buffers.py in set_buffer(self, buf, is_global)
    503             extra = (1,)
    504         shape = (-1,) + extra
--> 505         self._data = buf.reshape(shape).squeeze()
    506         self._data_coords_global = is_global
    507 

ValueError: cannot reshape array of size 2 into shape (49,2)
```
squeeze() is likely squeezing out the ds dimension.

**Comment by sk1p** [comment]
That's a nice edge case, good find!

**Comment by sayandip18** [comment]
> Process data with nav shape (1,), possibly with aux data

Is that the `extra_shape` in buffer declaration that is supposed to be (1,)?
