### ISSUE TITLE
Add GPU configuration to the GUI

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#803]
As continuation of #760: we should allow users to opt-in to GPU processing. What would be the best place to integrate this? I guess when starting the cluster? Or as a runtime configuration, where the user can enable/disable GPU processing after the fact?

I guess once we have a cluster connection, we can trust that the user created it with the right parameters, and use the GPU workers if available. So the first option would work well.

So integration steps would be:

- [x] add GPU information to the configuration that is returned on connection by the web API
- [x] add GPU checkboxes to the "make local cluster" form
- [x] send selected GPUs back to the web API and pass them to the cluster spec creation code

Does that sound right? If so, I think it is easy enough to do in 0.6, and I'll take a stab at it after #760 is merged, if no one else volunteers.

**Comment by uellue** [comment]
@sk1p sounds good! The `detect()` and `cluster_spec()` functions should make that relatively easy.
