### ISSUE TITLE
Correct function does not fix bad pixel

### ISSUE THREAD

**Issue by bangunarya** [LiberTEM/LiberTEM#818]
I recently tried to implement correction of bad pixel using correct function
```sig_shape = (256,256)```
```x =np.array([(240,174,206,143), (157,228,242,41)]).astype(np.int64)```
```data_new = correct(data, dark_image = None, gain_map = None, excluded_pixels = x, inplace = False, sig_shape = sig_shape)```

However, when summing all frames it seems the correct function does not change the specific bad pixel from the surrounding pixel. Is there something wrong with the implementation?
![image895](https://user-images.githubusercontent.com/47388866/85009555-e4175d00-b15e-11ea-9f30-f8d6f46509cc.png)

**Comment by uellue** [comment]
Hi @bangunarya Thx for the report! Can you perhaps include how you generated data and how you plotted it?

**Comment by sk1p** [comment]
I tried this with synthetic data, and it appears to work fine:

![image](https://user-images.githubusercontent.com/5778/85011899-7e2cd480-b162-11ea-88c4-c6991d2379ac.png)

**Comment by uellue** [comment]
In that case we should have a look at the entire notebook to see where the issue is.

**Comment by uellue** [comment]
It seems to have done *something* since the leftmost and rightmost pixel went from bright to dark.

**Comment by bangunarya** [comment]
> Hi @bangunarya Thx for the report! Can you perhaps include how you generated data and how you plotted it?

**Comment by bangunarya** [comment]
> Hi @bangunarya Thx for the report! Can you perhaps include how you generated data and how you plotted it?
Hi Dieter, here I attached the code. 
![tes](https://user-images.githubusercontent.com/47388866/85113464-9ca0d780-b217-11ea-952c-b8fafec321e6.png)

**Comment by uellue** [comment]
Thank you! I'll try it out next week and see what happens there.

**Comment by uellue** [comment]
@bangunarya Thx again for reporting! I could reproduce it, it was an issue with handling integer input data. PR #831 fixes this on my system.
