### ISSUE TITLE
fullmatcher test failures

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#826]
Three parallel failures on Linux (py36 and py37) - did something relevant change in the environment? Maybe the new numpy version? /cc @uellue 

https://travis-ci.com/github/LiberTEM/LiberTEM/jobs/351783792
https://travis-ci.com/github/LiberTEM/LiberTEM/jobs/351783793
https://travis-ci.com/github/LiberTEM/LiberTEM/jobs/351783800

**Comment by uellue** [comment]
I'll have a look this week.

**Comment by uellue** [comment]
Yes, this is triggered by upgrading to NumPy 1.19, I can reproduce it on moellenstedt.
