### ISSUE TITLE
Strange streaks in FFT analysis

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#836]
How to reproduce:

* LiberTEM version 0.5.0
* Use FFT analysis in the GUI on D:\Merlin_data\Janghyun\20200619 - SNBD Test\01_256X256_1ms_TV120/Test.hdr

Result:

![Capture](https://user-images.githubusercontent.com/25689052/86012437-42292780-ba1e-11ea-8aff-5863eeb1600a.PNG)

The streaks look like artifacts.

**Comment by sk1p** [comment]
Did you confirm that there is no artifact in the source data? Can you make this data set available to me, or should I have a look when I'm at the institute again?

**Comment by uellue** [comment]
> Did you confirm that there is no artifact in the source data?

I didn't go in depth with scripting. The leftmost panel looked very different between the positions with the streaks and the other areas, while the central "pick" frame looked the same. Janghyun told me that there was building work at the time, although I don't know how that should have caused the anomaly.

> Can you make this data set available to me, or should I have a look when I'm at the institute again?

Currently it is only on the Merlin PC. Maybe you or I can have a look when we are at the institute.

**Comment by sk1p** [comment]
> The leftmost panel looked very different between the positions with the streaks and the other areas

I think we need to have a detailed look at the absolute result values here to be sure

**Comment by uellue** [comment]
I could reproduce "funny" streaks in our `20200518 165148` Ptychography dataset:

![image](https://user-images.githubusercontent.com/25689052/98982390-a0632c80-251f-11eb-8ef7-5339fe0bb576.png)

The analysis runs quite unstable in a Jupyter notebook: It randomly hangs and crashes. This looks like a deeper issue?

**Comment by uellue** [comment]
Tracked it down: It is a bad pixel in the detector.

![image](https://user-images.githubusercontent.com/25689052/98988476-0653b200-2528-11eb-9622-3998bcd29ae3.png)

The instability seems to be caused by other factors, not sure what is going on.

**Comment by uellue** [comment]
Closing here since the issue is not related to LiberTEM, but an artifact in the data.
