### ISSUE TITLE
Copy remote cluster connection code

### ISSUE THREAD

**Issue by twentyse7en** [LiberTEM/LiberTEM#845]
If GUI is successfully connected to a remote cluster, the connection code will be
generated and an option to copy the code. Where would the ideal place for providing the option?

**Comment by sk1p** [comment]
I think this could be combined with a status display for the current cluster connection. Maybe in the menu bar somewhere? One option would be to put the "action"-like items ("About", "Shutdown") into a drop-down menu and display the cluster status in the top-right, where the shutdown button is right now. What do you think?

**Comment by twentyse7en** [comment]
Instead, can we put the cluster status to the left of "Shutdown"? What are the information to be displayed in the status?

**Comment by sk1p** [comment]
> Instead, can we put the cluster status to the left of "Shutdown"?

Could be possible - we just need to make sure the menu doesn't get too crowded, or, in other words, that the menu is stays clear and usable.

> What are the information to be displayed in the status?

Hmm, something like "connected to (local cluster|cluster URI), N CPU workers, M GPUs"? If you can think of a way to show this more concise, that would also be great. Then maybe a "copy" icon to show your copying component?
