### ISSUE TITLE
Test coverage for notebook generator

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#856]
A reminder that the notebook generation of the following analyses is not yet (fully) covered by test cases:

- [x] Clustering analysis (I think the code generation was not complete here, too?)
- [x] Radial Fourier analysis (I think this is waiting for the empyre stuff?)
- [x] Raw FFT (`PickFFTFrameAanlysis`) #858
- [x] `SumSigAnalysis` #858

Test coverage can be checked via the `htmlcov` directory after running the tests via tox, or (soon!) via [the new azure pipelines pages](https://dev.azure.com/liberTEM/LiberTEM/_build/results?buildId=20&view=codecoverage-tab)

**Comment by twentyse7en** [comment]
`Radial Fourier Analysis` notebook requires the `empyre`, so the test is currently skipped. `Cluster Analysis` notebook generation is incomplete.

**Comment by sk1p** [comment]
I think this is done, closing.
