### ISSUE TITLE
Improve notebook generator

### ISSUE THREAD

**Issue by twentyse7en** [LiberTEM/LiberTEM#859]
* [x] Fix cluster analysis notebook generation
* [x] Option to copy and paste cells instead of downloading

**Comment by twentyse7en** [comment]
Is this general design okay?


![2020-07-30_18-03](https://user-images.githubusercontent.com/59721339/88923359-39cb4300-d28f-11ea-8fae-f5e970acadaf.png)

**Comment by sk1p** [comment]
Looks good to me!

As an addition, it could be nice to be able to copy the whole source code in one go, what do you think? Also, maybe provide a "download as Jupyter Notebook" button/link in the header of this modal, too?

**Comment by twentyse7en** [comment]
> As an addition, it could be nice to be able to copy the whole source code in one go

If that's useful, no problem in adding that :+1:

**Comment by sk1p** [comment]
@twentyse7en I think with #864 merged, this issue is done, right?

**Comment by twentyse7en** [comment]
> @twentyse7en I think with #864 merged, this issue is done, right?

Yes

**Comment by sk1p** [comment]
Thanks!
