### ISSUE TITLE
benchmarks/corrections/test_corrset.py throws ValueError

### ISSUE THREAD

**Issue by AnandBaburajan** [LiberTEM/LiberTEM#868]
`ValueError: invalid entry in coordinates array` on running the benchmark test

**Comment by sk1p** [comment]
Interesting, I think this is a typo here:

https://github.com/LiberTEM/LiberTEM/blob/71eb1a18895f72654f6671442c40ca2c32f6257c/benchmarks/corrections/test_corrset.py#L33

That should be `(1024, 1024)`. I'll quickly open a PR for this.

**Comment by sk1p** [comment]
Thanks for reporting, it should be fixed now!
