### ISSUE TITLE
Show coordinates of frame picker in GUI

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#87]
To combine work with Simple API and GUI, one sometimes has to find out the exact coordinates of a specific frame. The "Pick" mode works nicely to show the frame. Below the picking window, the GUI should show the coordinates of the frame that is picked.

**Comment by sk1p** [comment]
While working on the frame picker: it should also position the marker into the center of the picked pixel. Right now, it snaps to the top left.
