### ISSUE TITLE
Update install documentation to use `python3 -m pip`

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#892]
See https://snarky.ca/why-you-should-use-python-m-pip/

For some reason, I have to do it like that on moellenstedt after Python was updated. Using `pip install <...>` tries to install with Python 2 in the wrong environment. That means this issue is real and updating our documentation can help to steer newer users away from potential trouble.

**Comment by uellue** [comment]
Assigning to 0.6 since this is a relatively minor update and we can do it as part of documentation QA during the release process.

**Comment by pragat-pandya** [comment]
I would like to work on this issue, Please assign this task to me!

**Comment by sk1p** [comment]
> I would like to work on this issue, Please assign this task to me!

Sure thing, please let me know if you need any help!
