### ISSUE TITLE
GUI/client dev on Firefox stuck in reconnect loop

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#907]
See #870 for discussion of the problem. WebSocket doesn't connect, stuck in a reconnect loop. Root cause is still unknown, needs to be debugged.

**Comment by uellue** [comment]
Still reproducible on Windows with current `node`  and Firefox 91.11.0esr (64-bit)

**Comment by sk1p** [comment]
Same on Linux - possibly an issue in create-react-app / webpack-dev-server / ... when proxying the websocket connection.

**Comment by uellue** [comment]
Seems to have fixed itself, could not reproduce on current system and Firefox.
