### ISSUE TITLE
Visualization: remove outliers before normalization

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#925]
If there are unusually large outliers, the default visualization is significantly impacted, as they throw off the normalization:

![image](https://user-images.githubusercontent.com/5778/102081706-f245ed80-3e10-11eb-8b03-23f2432535e7.png)

Something like [these functions in libertem-holo](https://github.com/LiberTEM/LiberTEM-holo/blob/43363ebdb749ec3e792c58ada98e723d09ec4070/src/libertem_holo/base/filters.py#L14-L31) could be useful.

**Comment by uellue** [comment]
The issue comes from negative values in combination with log scaling. Since negative values can't be represented well in a log scaled plot, they are shown as black by matplotlib.

**Comment by uellue** [comment]
Discussion with @sk1p: My bad, this was on the right where we have linear scaling. It is in fact an outlier that drags all other values to the very bottom of the color scale.

**Comment by sk1p** [comment]
Interim solution: for virtual detector analyses, in addition to linear scale output, also output a layer with a log-scaled visualization. As opposed to just patching out the outliers, this would allow to view data with high dynamic range without loss of information.

Medium-term: allow to set normalization parameters in client. Has about four steps:
- get vmin/vmax information to the client
- visualization update endpoint (could be a simple "synchronous" GET request that returns the visualization result for given parameters)
- update state management to allow to update visualization results
- add GUI elements to change visualization parameters

Long-term: #134
