### ISSUE TITLE
Make displayed and actual point analysis coordinates match

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#926]
## How to reproduce

* LiberTEM current master, possibly older versions as well
* Open a low-resolution dataset, for example 32x32x32x32, with clearly identifiable points (in this case a double diagonal with outliers).
* Perform a point analysis around the outliers. Disk analysis and frame picking are not affected, others not tested.

## Expected results

* A pixel on the left is selected if the center of the crosshair is within it.
* As a bonus, the selector position could snap to pixel centers like it does for frame picking.

## Observed result

* The selection area for a pixel seems to be shifted by 1/2 to the lower right. Based on the numerical values, one should use "round()" instead of "floor()" to get the integer point position from float coordinates.

See these pictures:

### Centered: correct pixel
![Capture-centered](https://user-images.githubusercontent.com/25689052/102088817-b9f7dc80-3e1b-11eb-9467-37bdca811f77.PNG)
### Lower left corner: Wrong pixel selected
![Capture-lower-left](https://user-images.githubusercontent.com/25689052/102088842-bf552700-3e1b-11eb-8dcc-78adaa59f2f5.PNG)
### Lower right corner: Correct pixel selected
![Capture-lower-right](https://user-images.githubusercontent.com/25689052/102088852-c1b78100-3e1b-11eb-87b6-3023f4bf9f0d.PNG)
### Upper right corner: Wrong pixel selected
![Capture-upper-right](https://user-images.githubusercontent.com/25689052/102088858-c3814480-3e1b-11eb-894a-2cd75f1f65d6.PNG)
### Upper left corner: Pixel to the upper left selected (wrong pixel, other outlier)
![Capture-upper-left](https://user-images.githubusercontent.com/25689052/102088868-c67c3500-3e1b-11eb-97ec-a67b8de2980e.PNG)
### Just below pixel: Still within selection
![Capture-below](https://user-images.githubusercontent.com/25689052/102088873-c8de8f00-3e1b-11eb-8439-de62dfdc46b7.PNG)
### Just right of pixel: Still selected
![Capture-right](https://user-images.githubusercontent.com/25689052/102088898-ced47000-3e1b-11eb-8b4f-15f246b06697.PNG)

**Comment by sk1p** [comment]
Thanks for the detailed report, this should be fixed in #927
