### ISSUE TITLE
Documentation, test case and example for UDFMeta.coordinates

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#928]
As a follow-up to #793, we should refine the newly introduced feature. A good candidate to use this in practice is SSB in https://github.com/Ptychography-4-0/ptychography

**Comment by uellue** [comment]
In use in https://github.com/Ptychography-4-0/ptychography/, can serve as an example

**Comment by AnandBaburajan** [comment]
> In use in https://github.com/Ptychography-4-0/ptychography/, can serve as an example

I've written some tests [here](https://github.com/LiberTEM/LiberTEM/blob/master/tests/udf/test_coords.py) and little documentation [here](https://libertem.github.io/LiberTEM/reference/udf.html#libertem.udf.base.UDFMeta.coordinates). I'm not sure if I should write application-specific (would need to understand ptychography?) documentation and examples.

**Comment by sk1p** [comment]
Hmm, I think it could be useful to also have a paragraph or two in the non-reference documentation, maybe as part of the ["advanced UDFs" section](https://libertem.github.io/LiberTEM/udf/advanced.html#meta-information)? Doesn't have to be a complex example - maybe just informing the user that the coords are there.

@uellue can you think of a simpler example that approximates something that would be used in the wild? Maybe a simple example of descan correction?
