### ISSUE TITLE
Docs: Mention that UI changes require restarting the server AND reloading the GUI

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#93]
If you restart the server, the GUI reconnects automatically. However, it still uses the older version of the JavaScript code in that case. You have to reload the GUI in the browser to get the most recent version.

**Comment by sk1p** [comment]
In addition: both Python and JavaScript code should have the git revision embedded. When the client connects to the server, it can check if the versions match and show a reload button if they don't match.

**Comment by uellue** [comment]
@sk1p f966d48 will of course only close the docs aspect of this issue. I only saw your comment about the version after committing and creating the pull request.
