### ISSUE TITLE
Context.load('auto', ...) silently swallows keyword arguments, at least for FRMS6

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#936]
How to reproduce:

Open an FRMS6 dataset with embedded dark frames and try to disable offset correction with the option `enable_offset_correction=False`.

## Observed behavior

With `Context.load('frms6', path=..., enable_offset_correction=False)`, the dataset is loaded and offset correction is disabled.

With `Context.load('auto', path=..., enable_offset_correction=False)`, the dataset is loaded, but offset correction is still enabled.

## Expected behavior

The offset correction is disabled also for type `'auto'`. Alternatively, an error can be raised. In any case, keyword arguments should not be silently ignored.

**Comment by sk1p** [comment]
Important to fix for 0.6, as we also hit this in the benchmark for the buffered reader, where the `io_backend` parameter was silently ignored, which caused just plain wrong results.
