### ISSUE TITLE
Validate file readers against alternative implementations

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#937]
In #932, some tests that use a form of snapshot testing are replaced with tests that validate against alternative file reader implementations to make the results more stable against numerical variations and consistent with other relevant packages.

A prototype notebook with alternative readers for all  formats except K2IS is included in that PR. However, only selected tests for DM, FRMS6 and MRC are converted yet which were affected by the numerical instability. The alternative readers should be included for other file format tests as well:

- [x] FRMS6 full file, not only beginning
- [x] DM full file and 3D DM
- [x] MRC full file
- [x] BLO
- [x] EMPAD
- [x] MIB
- [x] SEQ
- [x] SER
- [x] K2IS

**Comment by uellue** [comment]
Should we perhaps include a raw data version of K2IS generated with the 0.5 release as a snapshot and reference? At least we will catch changes!

**Comment by sk1p** [comment]
> Should we perhaps include a raw data version of K2IS generated with the 0.5 release as a snapshot and reference? At least we will catch changes!

Sounds like a plan! :+1:

**Comment by uellue** [comment]
Other formats are covered as well now, this issue will be closed with #932.
