### ISSUE TITLE
LiberTEM web GUI: GPU only used after deselecting and selecting again

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#948]
# How to reproduce

Use `libertem-server` on a system with CUDA GPU and working CuPy, Windows 10, Chrome 88.0.4324.104, and start a local cluster.

# Observed behavior

The GPU seems to be selected by default. When launching the cluster without further interaction, the cluster status doesn't show GPU workers, however.

If the GPU is first deselected and then selected again before starting the cluster, the cluster status shows the GPU worker.

# Expected behavior

If the GPU is selected, the cluster will always start with a GPU worker.

**Comment by sk1p** [comment]
FYI I'm now looking into this, but may take a while, since I also want to fix my CUDA setup, to do some realistic tests.
