### ISSUE TITLE
Read performance with HDF5, Windows 10, HDD

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#971]
## How to reproduce

Run the "center of mass" example with the EMD file from a HDD on Windows.

## What happens

Read speed is about 17 MB/s on my system, while the HDD is capable of about 117 MB/s using LiberTEM with the buffered reader.

## What should happen

Read perfromance of HDF5 should be in the same order of magnitude as other file formats.

**Comment by sk1p** [comment]
Could you try if the linked PR fixes/improves this issue? As the file is chunked, we don't have many options, but this change is kind of a low-hanging fruit.

On my system, this goes from taking 15s cold to being as fast as processing a raw file. Before:

```
14.963273048400879 - cold EMD
0.8389596939086914 - hot EMD
11.765928745269775 - cold RAW
0.3656883239746094 - hot RAW
```

After:

```
11.2949378490448 - cold EMD
0.77344202995300 - hot EMD
11.7877163887023 - cold RAW
0.29714965820312 - hot RAW
```
