### ISSUE TITLE
Release 0.7

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#985]
## Issues that should be part of this release:

- [x]  #1001 - follow-up for the `get_results` API, should be fixed before we have to support the "old" way
- [x] #1000 - can be fixed together with #1001

## QA checklist

<s>This is a point release, mostly for #984 since it fixes a severe performance issue with a localized change.</s>

Edit: Upgraded to full release, see comment below.

- [x] Review open issues and pull requests
- [x] Run complete test suite, including slow tests that are deactivated by default
  and tests that require sample files.
- [x] Update and review change log in :code:`docs/source/changelog.rst`, merging
  snippets in :code:`docs/source/changelog/*/` as appropriate.
- [x] Update the JSON files in the ``packaging/`` folder with author and project information
- [x] Review https://github.com/LiberTEM/LiberTEM/security/dependabot and update dependencies
- [x] Edit :code:`setup.cfg` to exclude flaky tests temporarily from release builds
- [x] Create a release candidate using :code:`scripts/release`. See :code:`scripts/release --help` for details.
- [x] `Confirm that wheel, tar.gz, and AppImage are built for the release candidate on
  GitHub <https://github.com/LiberTEM/LiberTEM/releases>`_
- [x] Confirm that a new version with the most recent release candidate is created in the
  `Zenodo.org sandbox <https://sandbox.zenodo.org/record/367108>`_ that is ready for submission.
- [x] Install release candidate packages in a clean environment
  (for example:
  :code:`python -m pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple 'libertem==0.7.0rc0'`)
- [x] Correct version info displayed in info dialogue?
- [x] Link check in version info dialogue
- [x] Test on a full portfolio of HDF5 files
- [x] Open each test file
    - [x] Are parameters recognized correctly, as far as implemented?
    - [x] Any bad default values?
    - [x] Does the file open correctly?
    - [x] Have a look at the dataset info dialogue. Reasonable values?
- [x] Perform all analyses on each test file.
    - [x] Reasonable performance?
    - [x] Results look as expected?
    - [x] Use pick mode.
- [x] Run all examples that use HDF5 input data
- [N/A] Make sure that the Job interface and blobfinder still work, since they have been removed in the master branch for 0.7 already.
- [x] Run libertem-server on Windows, connect to a remote dask cluster running on Linux,
  open various HDF5 files and perform an analysis for each file type.
- [x] Confirm that pull requests and issues are handled as intended, i.e. milestoned and merged
  in appropriate branch.

## After releasing on GitHub

- [x] Confirm that all release packages are built and release notes are up-to-date
- [x] Install release package
- [x] Confirm correct version info
- [x] confirm package upload to PyPI
- [x] Publish new version on zenodo.org
- [ ] Update documentation with new links, if necessary
    - [ ] Add zenodo badge for the new release to Changelog page
- [x] Send announcement message on mailing list
- [x] Edit :code:`setup.cfg` to include flaky tests again
- [x] Bump version in master branch to next .dev0
- [x] Add the current LiberTEM version to
  `CVL <https://github.com/Characterisation-Virtual-Laboratory/CharacterisationVL-Software>`_ (add both the singularity and the .desktop file!)

**Comment by uellue** [comment]
A potential candidate for inclusion would be #982. However, that PR has a cross relation to the job interface removal and is not so urgent for real-world usability. I'd propose to leave that one for 0.7 to keep things simple.

**Comment by uellue** [comment]
We'll wait with the release for 1-2 weeks after #984 is merged since there were more changes necessary than anticipated and we'd like to see if any issues crop up when using LiberTEM.

**Comment by uellue** [comment]
@sk1p and I decided to do a release 0.7 with some of the recently merged new features since they will be useful for work in https://github.com/Ptychography-4-0/ptychography/pull/35/ and https://github.com/LiberTEM/LiberTEM-live

Scope TBD! @sk1p it should probably also include the live plotting parts with effects on the Analysis interface, as far as they affect LiberTEM and not LiberTEM-live? :-)

**Comment by sk1p** [comment]
> it should probably also include the live plotting parts with effects on the Analysis interface, as far as they affect LiberTEM and not LiberTEM-live? :-)

Agreed - I've added a TODO list to the top of this issue to keep track of the "release critical" issues.

**Comment by sk1p** [comment]
https://github.com/nbQA-dev/nbQA

https://github.com/computationalmodelling/nbval
