### ISSUE TITLE
Tileshapes refactor

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#99]
Currently, we have tiles that are always 4D shapes. This is a problem if the number of frames per tile doesn't evenly divide the scan width: tiles near the right edge will not be of the same shape as others. Example:

Dataset shape: `(16, 16, 128, 128)`
Tileshape: `(1, 6, 128, 128)` 

For the first row, we will have three tiles. The first two will have shape `(1, 6, 128, 128)`, the last one `(1, 4, 128, 128)`. That means for the whole right border we have potentially inefficient cache usage while applying masks.

We can fix this by using 3D tileshapes: they can "spill over" into the next row of frames.

Pro: 
- other than the very last tile, they will all be of the same shape
- less logic for the borders in dataset implementations
- processing non-rectangular scans is easier

Con: 
- no easy way to have a local environment of frames in one go (note that this is also not yet possible for all readers: HDF5 and mmap'ed readers could easily support this, others need some work)

The idea would be to support both 3D and 4D tiles and use the most appropriate for the current job.

**Comment by uellue** [comment]
I guess #195 closes this?
