### ISSUE TITLE
Improve Python API docs

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#990]
- Add a list of functionality: deep links into the reference (at the top) --> postponed via #638 
- [x] Explanation of `functools.partial`
- [x] Integrate the UDF notebook into the UDF docs
- [x] Address https://github.com/Ptychography-4-0/ptychography/issues/44 for LiberTEM (drive-by)

**Comment by uellue** [comment]
See also https://github.com/Ptychography-4-0/ptychography/issues/44 for a docs TODO!
